Add Edit button in twin details page.
threefoldtech/tfgrid-sdk-ts pull request #1051
Opened 2023-08-27 13:15 UTC by AlaaElattar

- The button won't appear unless the relay or pk don't match target ones.
- Then, user can update relay and pk will be updated internally.
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1014

- If there's no edit button
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/4b71f600-9c6e-4364-b35f-ecc73ec02774)

- If there's edit button
![Screenshot from 2023-08-27 16-14-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/fc5af1df-8721-4c8d-a7bf-5f1450ebf808)
![Screenshot from 2023-08-27 16-14-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/67397934-5fba-4385-b25c-e45226cfec49)

2023-08-28 08:44 UTC, AhmedHanafy725 commented on packages/playground/src/portal/twin_view.vue
> +  const client = new GridClient({ mnemonic: profileManager.profile!.mnemonic, network: window.env.NETWORK });
do we use the client here?

2023-08-28 08:44 UTC, AhmedHanafy725 commented on packages/playground/src/portal/twin_view.vue
> +    await twins.update({ pk: newPk, relay: relay.value });
we can use the twin module here on the grid client if we already have it.
`grid.twins.update` and it doesn't need pk, it's already updating it

2023-08-28 08:44 UTC, AhmedHanafy725 commented on packages/playground/src/portal/twin_view.vue
> +    console.log("could not update relay or pk, Error: ", e);
in case the update fails, we should show the error to the user

2023-08-31 12:51 UTC, AhmedHanafy725 commented on packages/playground/src/portal/twin_view.vue
> +    profileManager.updateRelay(window.env.RELAY_DOMAIN);
why the profile's relay and the twin's relay are not updated with the same value?

2023-09-03 11:56 UTC, zaelgohary requested changes

2023-09-03 11:56 UTC, zaelgohary commented on packages/playground/src/portal/twin_view.vue
> +        </v-card-actions>
```suggestion
        <v-card-actions v-if="updateRelay" class="justify-end mx-4 mb-4">
          <v-btn color="primary" class="custom-button bg-primary" @click="editTwin">Edit</v-btn>
        </v-card-actions>
```

2023-09-03 11:56 UTC, zaelgohary commented on packages/playground/src/portal/twin_view.vue
> +    const pk = await generatePublicKey(profileManager.profile!.mnemonic);
Instead of generating a new PK, can we get the existing one from the client? As the value of the generated PK might not match the one on the grid.

2023-09-03 11:56 UTC, zaelgohary commented on packages/playground/src/portal/twin_view.vue
> +    const newPk = await generatePublicKey(profileManager.profile!.mnemonic);
Also here, we can get the existing pk and store it in profile manager

2023-09-03 13:59 UTC, zaelgohary approved these changes

2023-09-03 14:04 UTC, merged