Adding stats page to playground
threefoldtech/tfgrid-sdk-ts pull request #1063
Opened 2023-08-30 17:02 UTC by maayarosama

### Description

Adding statistics page to the playground
### Changes

Adding a ```StatisticsCard``` components and a stats view.
### Related Issues

#1022
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-09-03 20:35 UTC, xmonader requested changes
I think there could be some improvements e.g the icon and the title should be on the same row, and a different bigger font for the values imo

@ehab-hassan please check

2023-09-04 10:03 UTC, ehab-hassan commented
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b4894f3b-30cb-4e9a-b632-d4240e1e804e)
 @xmonader stats updated

2023-09-04 10:10 UTC, xmonader commented
@ehab-hassan can we make the titles standout a little bit? it feels so pale in the card

2023-09-04 10:42 UTC, ehab-hassan commented
@xmonader as we agreed let's keep the user's eyes focused on the numbers first, Thanks

2023-09-05 10:42 UTC, ehab-hassan commented
as I agreed with @xmonader we ll keep it as is, Thanks

2023-09-10 13:41 UTC, zaelgohary requested changes
Great work! Just a few comments on the design.

2023-09-10 13:41 UTC, zaelgohary commented on packages/playground/src/components/statistics_card.vue
> +      </div>
```suggestion
      <div class="d-flex align-center justify-center items-center py-2 font-weight-bold fs-17">
        <v-icon class="mr-3" size="large">{{ item.icon }} </v-icon>
        <span>
          {{ item.title }}
        </span>
      </div>
```

2023-09-10 13:41 UTC, zaelgohary commented on packages/playground/src/components/statistics_card.vue
> +</script>
```suggestion
</script>

<style scoped>
.fs-17 {
  font-size: 1.1rem;
}
</style>
```

2023-09-10 13:41 UTC, zaelgohary commented on packages/playground/src/portal/stats.vue
> +  padding: 15px 16px 0;
Please remove the padding here.
```suggestion
```

2023-09-10 13:41 UTC, zaelgohary commented on packages/playground/src/router/index.ts
> +    {
Why is the twin view added here?

2023-09-10 13:41 UTC, zaelgohary commented on packages/playground/src/portal/stats.vue
> +      /* Pass */
I think we need to handle the error here.

2023-09-10 13:42 UTC, zaelgohary commented
Also, can you pull the latest changes from the base branch?

2023-09-10 13:49 UTC, zaelgohary commented on packages/playground/src/portal/stats.vue
> +        <v-col cols="10" class="mx-auto"> <tf-map :nodes="nodesDistribution"></tf-map></v-col>
Can we change the colors of the nodes here as it's not in the palette we use?

2023-09-17 09:30 UTC, MohamedElmdary commented on packages/playground/src/components/statistics_card.vue
> +.fs-17 {
Please use vuetify typo classes and remove fs-17 as it's name is meanless
https://vuetifyjs.com/en/styles/text-and-typography/

2023-09-17 09:36 UTC, MohamedElmdary commented on packages/playground/src/portal/stats.vue
> +
use gridProxyClient instead which provide a type support check
`packages/playground/src/clients/index.ts`

2023-09-17 09:37 UTC, MohamedElmdary commented on packages/playground/src/portal/stats.vue
> +}
Use vuetify flex classes and media helpers

2023-09-19 13:02 UTC, MohamedElmdary commented on packages/playground/src/portal/stats.vue
> +            <StatisticsCard :item="item" />
```suggestion
          <v-col v-for="item of Istats" :key="item.title" xl="2" lg="3" md="4" sm="6" cols="12" class="px-2">
            <StatisticsCard :item="item" />
```

As vuetify is mobile first approach so there is no `xs` attribute it's refered to `cols`

2023-09-20 12:53 UTC, maayarosama commented
Last commit changes:
- Using  type Stats from "@threefold/gridproxy_client" instead of defining my own.
- Removing the condition that made the map visible only when there's no Istats.
- Changing the map's colors.
- Adding a retrytofetchstats method and a refresh button in case of failure.
![Screenshot from 2023-09-20 15-48-08](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/c6dd3ecc-7976-4c3c-bd31-8bb57f3c1905)

2023-09-24 08:44 UTC, MohamedElmdary approved these changes

2023-09-24 09:20 UTC, zaelgohary commented on packages/playground/src/portal/stats.vue
> +  const fetchDataWithRetry = async (): Promise<Stats> => {
Promise return type might be undefined in case it entered catch. You can change the type to Promise<Stats | undefined> or adjust the function logic.

2023-09-24 09:44 UTC, zaelgohary approved these changes

2023-09-24 09:47 UTC, merged