Development 313 offline nodes notifacation
threefoldtech/tfgrid-sdk-ts pull request #1239
Opened 2023-10-18 13:39 UTC by Mahmoud-Emad

### Description

- Added a notification helper that will notify the user every 2 hours if there are deployments on an offline node.
- Updated the toast warning background, icon color, and text color in dark/light mode.   

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1220

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-10-22 09:06 UTC, AhmedHanafy725 requested changes

2023-10-22 09:06 UTC, AhmedHanafy725 commented on packages/playground/src/utils/custom_toast.ts
> +    const closIcons = document.getElementsByClassName("mosha__toast__close-icon");
```suggestion
    const closeIcons = document.getElementsByClassName("mosha__toast__close-icon");
```

2023-10-22 09:14 UTC, Mahmoud-Emad commented on packages/playground/src/components/tf_notification.vue
> +  userContracts.nodeContracts.map((contract: any) => {
Which type should be used?

2023-10-24 06:46 UTC, AhmedHanafy725 approved these changes

2023-10-24 10:42 UTC, 0oM4R requested changes
![Screenshot from 2023-10-24 13-37-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/9c136ea8-b54c-49d7-9c4e-0b56d69f9401)

looks like we have an issue with the colors in dark mode can you check this ?

2023-10-24 11:30 UTC, 0oM4R approved these changes
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/1aaf705f-cfca-409c-af47-2b127e17cc35)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/b22f2257-1d0e-4bfe-b068-e6b74da4e207)

Great work!

2023-10-24 11:31 UTC, 0oM4R commented
i beli

> ![Screenshot from 2023-10-24 13-37-57](https://user-images.githubusercontent.com/62248851/277632903-9c136ea8-b54c-49d7-9c4e-0b56d69f9401.png)
> 
> looks like we have an issue with the colors in dark mode can you check this ?

it was cached somehow worked fine after that

2023-10-24 11:34 UTC, merged