add ping node utils and update tests
threefoldtech/tfgrid-sdk-ts pull request #1258
Opened 2023-10-22 15:21 UTC by A-Harby

### Description

Add the Ping node function in utils to check every node that will be used in the tests before using it, preventing false-failing tests.

2023-10-22 15:33 UTC, xmonader requested changes
there's a pingNode function available on the client https://github.com/threefoldtech/tfgrid-sdk-ts/blob/e36762084aa34cc13a46c7141de0789ae244461f/packages/grid_client/src/modules/zos.ts#L46


P.S don't name functions `checkNodeAvail` it's incomplete and doesn't communicate the meaning

2023-10-23 07:40 UTC, A-Harby commented
> there's a pingNode function available on the client
> 
> https://github.com/threefoldtech/tfgrid-sdk-ts/blob/e36762084aa34cc13a46c7141de0789ae244461f/packages/grid_client/src/modules/zos.ts#L46
> 
> P.S don't name functions `checkNodeAvail` it's incomplete and doesn't communicate the meaning

I'm using pingNode function to check node state and return its ID.
  
Updated function name https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1258/commits/30e3cb2a9dc9df986464eaa9c7c11b6719b59021

2023-10-29 13:00 UTC, 0oM4R commented on packages/grid_client/tests/utils.ts
> +    log("No nodes available with the needed resources for this test");
is this function for test scripts only ?

2023-11-05 10:59 UTC, AhmedHanafy725 requested changes

2023-11-16 10:32 UTC, AhmedHanafy725 approved these changes

2023-11-16 11:30 UTC, mohamedamer453 approved these changes
Lgtm, and i ran the tests locally and everything went smoothly and passed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a6f69036-bd38-4f89-8c98-e6e97ae8df1b)

2023-11-16 14:57 UTC, merged