Development 313 enhance ui2
threefoldtech/tfgrid-sdk-ts pull request #1266
Opened 2023-10-23 20:37 UTC by ehab-hassan

Removed all containers and made it take the full width to make it consistent with tables in Nodes and Dedicated Nodes 
I also added a border and fixed some colors and font sizes. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/43d85a3b-3148-4fe2-b9de-74c70ef660ba)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a5c1ddcf-e443-4583-887a-aa7c29f70920)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/3e485073-b279-4d71-84bf-ab917bc8b6a1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/e8943138-bc7f-4ffa-83b2-6b884d1331f7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b94e3506-3530-420e-9bca-c439cb720cb4)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/256252bd-8b1d-4d69-bac7-33b14ee59fd0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/4084b0a0-bb36-435e-974a-7736d0ee65ad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/caad46e7-5c95-47ce-9f6d-de3a3e7f554a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/01e5fc94-42dc-4185-8e97-7c4a0f36f2cd)

2023-10-25 10:22 UTC, zaelgohary requested changes
Great job! just some minor comments that need to be taken into consideration.

2023-10-25 10:22 UTC, zaelgohary commented on packages/playground/src/explorer/views/nodes.vue
> +<style>
Can we make this scoped style?

2023-10-25 10:22 UTC, zaelgohary commented on packages/playground/src/portal/dedicated_nodes_view.vue
> +<style>
Also, can we make this scoped style?

2023-10-25 10:46 UTC, maayarosama approved these changes

2023-10-26 09:04 UTC, zaelgohary approved these changes

2023-10-26 12:29 UTC, merged