Development 313 failed deployments fix
threefoldtech/tfgrid-sdk-ts pull request #1268
Opened 2023-10-24 08:55 UTC by maayarosama

### Description

making sure that chunk3 isn't empty before adding it to failedDeployments
### Changes

List of changes this PR includes

### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1267
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-10-24 09:02 UTC, AlaaElattar approved these changes

2023-10-24 09:10 UTC, zaelgohary approved these changes

2023-10-24 09:59 UTC, AhmedHanafy725 commented on packages/playground/src/components/vm_deployment_table.vue
> +    ...(chunk3.count !== 0 ? (chunk3 as any).failedDeployments : []),
what about the other chunks? Don't have the same case?

2023-10-30 08:33 UTC, zaelgohary requested changes

2023-10-30 08:33 UTC, zaelgohary commented on packages/playground/src/components/k8s_deployment_table.vue
> +    ...(Array.isArray((chunk3 as any).failedDeployments) ? (chunk3 as any).failedK8s : []),
Can't we do sth like this instead?
```suggestion
    ...((chunk1 as any).failedK8s ?? []),
    ...((chunk2 as any).failedK8s ?? []),
    ...((chunk3 as any).failedK8s ?? []),
```

2023-10-30 08:35 UTC, zaelgohary commented on packages/playground/src/components/vm_deployment_table.vue
> +    ...(Array.isArray((chunk3 as any).failedDeployments) ? (chunk3 as any).failedDeployments : []),
Also here,
```suggestion
    ...((chunk1 as any).failedDeployments ?? []),
    ...((chunk2 as any).failedDeployments ?? []),
    ...((chunk3 as any).failedDeployments ?? []),
```

2023-10-30 10:32 UTC, zaelgohary approved these changes

2023-10-30 14:18 UTC, merged