Support offline node contract notification on `mainnet`
threefoldtech/tfgrid-sdk-ts pull request #1297
Opened 2023-10-29 08:38 UTC by Mahmoud-Emad

This is open to be attached to the `mainnet` as a patch release.

### The original issue description

> #### Description

> - Added a notification helper that will notify the user every 15 minutes if there are deployments on an offline node.
> - Updated the toast warning background, icon color, and text color in dark/light mode.   

> #### Related Issues

> - https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1220

> #### Screenshots

> - ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/9f2c31c9-f01b-4810-8b17-ee30f10c0fa1)

2023-10-29 23:24 UTC, amiraabouhadid requested changes
Please adjust the notification colors. I could not even read what is written in them. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/befd8e49-8927-458e-81dd-744d49fd8d9a)

2023-10-30 05:47 UTC, Mahmoud-Emad commented
@amiraabouhadid try to clear your cache keda

2023-10-30 07:58 UTC, 0oM4R commented
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/7feadadc-84f3-4dd6-b072-17c421f88ab4)
working fine with me, I think it will be better to close that toast by clicking on the contracts link, as the user will be redirected the contracts list page.

2023-10-30 10:20 UTC, AhmedHanafy725 requested changes

2023-10-30 10:20 UTC, AhmedHanafy725 commented on packages/grid_client/src/clients/tf-grid/contracts.ts
> +  billReports: GqlContractBillReports[];
```suggestion
  contractBillReports: GqlContractBillReports[];
```

2023-10-30 10:20 UTC, AhmedHanafy725 commented on packages/grid_client/src/clients/tf-grid/contracts.ts
> +      const billReports = gqlConsumption.billReports;
```suggestion
      const billReports = gqlConsumption.contractBillReports;
```

2023-10-30 12:12 UTC, Mahmoud-Emad commented
> ![image](https://user-images.githubusercontent.com/62248851/278975652-7feadadc-84f3-4dd6-b072-17c421f88ab4.png) working fine with me, I think it will be better to close that toast by clicking on the contracts link, as the user will be redirected the contracts list page.

Done :)

2023-10-30 13:55 UTC, 0oM4R approved these changes
Great job thank you!

2023-10-31 09:42 UTC, AhmedHanafy725 approved these changes

2023-10-31 09:46 UTC, AlaaElattar commented
- worked fine with me.

2023-10-31 09:46 UTC, AlaaElattar approved these changes

2023-10-31 09:58 UTC, amiraabouhadid approved these changes

2023-10-31 10:02 UTC, merged