Development 313 login UI color
threefoldtech/tfgrid-sdk-ts pull request #1346
Opened 2023-11-02 11:10 UTC by ehab-hassan

- changed the theme to match the new playground.
- moved (close button) to the right of the Login button.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/dd407a56-3c2e-4370-ae99-070dbc5f0b90)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/f6d7d582-59a5-4ec0-bd1a-141e3593709d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/70150280-ffd5-426e-86bf-c545f27cbe2a)

2023-11-05 09:18 UTC, amiraabouhadid requested changes

2023-11-05 09:18 UTC, amiraabouhadid commented on packages/playground/src/components/weblet_layout.vue
> +    <!-- <v-divider :class="{ 'mb-2': true, 'mt-5': !!$slots.subtitle, 'mt-2': !$slots.subtitle }" /> -->
please remove commented out code

2023-11-05 09:18 UTC, amiraabouhadid commented on packages/playground/src/weblets/profile_manager.vue
> +      <!-- <template #title> Connect your TFChain Wallet </template> -->
please remove this as well

2023-11-05 09:18 UTC, amiraabouhadid commented on packages/playground/src/weblets/profile_manager.vue
> +      <!-- <template #subtitle>
here too

2023-11-09 12:49 UTC, mohamedamer453 commented on packages/playground/src/weblets/profile_manager.vue
> +      <!-- <template #title> Connect your TFChain Wallet </template> -->
A commented line still needs to be removed

2023-11-09 13:29 UTC, mohamedamer453 approved these changes

2023-11-09 14:22 UTC, zaelgohary reviewed
Form validation works once I click on connect tab.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c62de6f7-cbd5-4d9a-949d-7eac522f6c47)

2023-11-09 14:32 UTC, zaelgohary requested changes

2023-11-09 14:32 UTC, zaelgohary commented on packages/playground/src/weblets/profile_manager.vue
> +                Scan the QRcode using
```suggestion
                Scan the QR code using
```

2023-11-14 13:12 UTC, zaelgohary commented
> Form validation works once I click on connect tab.
> 
> ![image](https://user-images.githubusercontent.com/40770501/281761795-c62de6f7-cbd5-4d9a-949d-7eac522f6c47.png)

Will be discarded as this PR handles the UI changes only.

2023-11-15 08:46 UTC, zaelgohary approved these changes

2023-11-16 14:29 UTC, amiraabouhadid approved these changes

2023-11-16 14:33 UTC, merged