Adding a certified chip and loading all nodes regardless of filters a…
threefoldtech/tfgrid-sdk-ts pull request #1366
Opened 2023-11-05 12:09 UTC by maayarosama

### Description

Initializing certified to undefined so all nodes could load at the start regardless of the certified filter and adding a chip for certified nodes
![Screenshot from 2023-11-05 14-08-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/df73add3-3a2b-40f4-b7e6-043ac09b1a71)
### Changes
- Initializing certified variable to undefined in all solutions
- Adding a certified variable to INode interface
- Adding a chip and a chip color to certified nodes

### Related Issues
#1091
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-11-05 13:44 UTC, zaelgohary reviewed
Now all certified nodes are being returned even if it's set to false.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/5a559205-f9ca-48b6-8949-ae7d160341c9)

2023-11-09 15:16 UTC, mohamedamer453 reviewed
Selecting a certified node without enabling the certified filter will not update the calculated resource pricing which is supposed to be 25% higher for certified nodes.

- Selecting a certified node without enabling the certified filter

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a7d0593a-d10a-4cfa-9f5c-c68f287d90ed)

- Selecting the same certified node but with the certified filter enabled.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1ed61eef-01de-4e13-bd6c-41bb622c601b)

2023-11-12 13:27 UTC, maayarosama commented
> Now all certified nodes are being returned even if it's set to false.
> 
> ![image](https://user-images.githubusercontent.com/40770501/280530570-5a559205-f9ca-48b6-8949-ae7d160341c9.png)

As per a discussion with @AhmedHanafy725 this's in fact the desired behavior.

2023-11-12 15:14 UTC, maayarosama commented
> Selecting a certified node without enabling the certified filter will not update the calculated resource pricing which is supposed to be 25% higher for certified nodes.
> 
> * Selecting a certified node without enabling the certified filter
>   ![image](https://user-images.githubusercontent.com/101194226/281778909-a7d0593a-d10a-4cfa-9f5c-c68f287d90ed.png)
> * Selecting the same certified node but with the certified filter enabled.
>   ![image](https://user-images.githubusercontent.com/101194226/281778472-1ed61eef-01de-4e13-bd6c-41bb622c601b.png)

Added a watch foe the selectedNode so that the calculator can recalculate when it changes.

2023-11-15 10:49 UTC, zaelgohary reviewed
Please pull latest changes from base branch as I can't review.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/be4e0624-31c7-4616-ab43-49d20dcd02f3)

2023-11-15 11:42 UTC, zaelgohary requested changes
As @mohamedamer453  mentioned, Same node has 2 different prices if the certified chip is enabled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/6d786b78-07c5-49b3-9a69-3863eb7085fd)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/aec48b8c-3fa8-4f45-909b-cfda736d841e)

2023-11-20 09:52 UTC, zaelgohary commented
Can you merge base branch? There was a build error and it was fixed.

2023-11-20 14:12 UTC, mohamedamer453 approved these changes

2023-11-20 14:27 UTC, zaelgohary requested changes

2023-11-20 14:27 UTC, zaelgohary commented on packages/playground/src/weblets/full_vm.vue
> +);
```suggestion
```

Can we remove this watcher? It's not needed.

2023-11-21 08:25 UTC, zaelgohary approved these changes

2023-11-21 08:31 UTC, merged