Support hex based seed
threefoldtech/tfgrid-sdk-ts pull request #1380
Opened 2023-11-08 09:35 UTC by MohamedElmdary

### Description
Support hex based seed in grid_client and migrate keys decryption to use new hex seed.

### Changes
- Migrate keys encryption from mnemonic(Aka. words) into hex seed.
- Update `rmb_direct_client`, `zos module` and `grid_client` to  load mnemonic as hex seed in keyring.
- Handle error in `playground` was thrown whenever we fail to load metadata due to unable to decrypt.

### Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/8

### Checklist
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-11-08 12:21 UTC, MohamedElmdary commented
After Adding the require hex based seed support 2 issue appeared. I think both of them might be caused by the same reason

- When trying to get a deployment
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/de0bd4c1-ba0b-4758-b2f2-80ed02e8c5c1)

- Trying to check if a node has enough storage pool
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/80fa4eda-5dc2-4202-a166-cdf06778ebda)

2023-11-09 12:06 UTC, Mahmoud-Emad approved these changes

2023-11-09 12:13 UTC, Mahmoud-Emad requested changes
Cant we change the validation in the dashboard as we did in the playground?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/6559f57f-7681-4a4c-85b9-f5024e732bf3)

2023-11-09 13:37 UTC, AhmedHanafy725 requested changes

2023-11-09 13:37 UTC, AhmedHanafy725 commented on packages/grid_client/src/helpers/utils.ts
> +function toHexSeed(mnemonic: string): string {
is the input only mnemonic? it can be hex seed, please rename it

2023-11-09 13:37 UTC, AhmedHanafy725 commented on packages/rmb_direct_client/lib/sign.ts
> +export function createShared(pubKey: Uint8Array, hexSeed: string) {
any user can use this client without using the grid client, we shouldn't make work on hex seed only. please handle the both cases

2023-11-09 13:37 UTC, AhmedHanafy725 commented on packages/grid_client/src/helpers/migration.ts
> +export async function migrateKeysDecryption(this: GridClient, GridClient: GridClientCtor): Promise<void> {
are we migrating decryption? please use a better name

2023-11-09 14:20 UTC, MohamedElmdary commented on packages/grid_client/src/helpers/utils.ts
> +    const keypair = box.keyPair.fromSecretKey(seed.slice(0, 32));
So how to get secretKey? @AhmedHanafy725

2023-11-12 11:51 UTC, AhmedHanafy725 commented on packages/rmb_direct_client/lib/sign.ts
> +  let privateKey: Uint8Array | string = hexSeedOrMnemonic.slice(2);
can we check its length and if it has 0x before slicing?

2023-11-13 12:11 UTC, Mahmoud-Emad approved these changes

2023-11-13 12:13 UTC, merged