Total Cost of contracts per hour and month
threefoldtech/tfgrid-sdk-ts pull request #1391
Opened 2023-11-09 10:10 UTC by AlaaElattar

### Description
- Showing total cost per hour and month

### Changes

- Add alert at the end of table showing total cost per hour or month.
- If there's no contracts, the alert won't appear

### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1359

![Screenshot from 2023-11-09 11-34-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/53b85134-47bf-452b-84c5-7e13b79456ba)

2023-11-09 10:28 UTC, amiraabouhadid commented
is it supposed to give 0 here? there are many contracts but the cost displayed is 0. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/307d63fb-5a83-4dda-9e50-2dc38fdf80da)

2023-11-09 10:29 UTC, amiraabouhadid requested changes

2023-11-09 10:29 UTC, amiraabouhadid commented on packages/playground/src/weblets/tf_contracts_list.vue
> +        >Total Cost: {{ totalCost }} TFT/hour ≈ {{ (totalCost * 24 * 30).toFixed(3) }} TFT/month</v-alert
you can just do `v-if="contracts.length"`

2023-11-09 10:42 UTC, AlaaElattar commented
> is it supposed to give 0 here? there are many contracts but the cost displayed is 0. ![image](https://user-images.githubusercontent.com/56790126/281700307-307d63fb-5a83-4dda-9e50-2dc38fdf80da.png)

I can check also if the `totalCost` is zero so i won't show the dialog. what do u think of this ?

2023-11-09 13:41 UTC, AhmedHanafy725 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +      totalCost.value += value;
please use `Decimal` in any money calculations

2023-11-09 14:37 UTC, zaelgohary approved these changes

2023-11-12 11:54 UTC, AlaaElattar commented on packages/playground/src/weblets/tf_contracts_list.vue
> +      totalCost.value += +value;
so u want `totalCost` to be of type `Decimal` ?

2023-11-12 11:59 UTC, AhmedHanafy725 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +      totalCost.value += +value;
no, you can do the calculation with Decimal and then convert it to a number at the end to show it to the user

2023-11-12 12:29 UTC, AhmedHanafy725 approved these changes

2023-11-12 13:55 UTC, xmonader commented on packages/playground/src/weblets/tf_contracts_list.vue
> +function getTotalCost(contracts: NormalizedContract[]) {
I believe we should introduce the raw field instead along with the consumption string, so field `tftPerHour` on the normalized contract object, and drop the regex part

2023-11-12 13:55 UTC, xmonader requested changes
Added a change request, let me know if you guys still want to proceed with the regular expression and why.

2023-11-13 12:06 UTC, xmonader approved these changes
Looks much cleaner now 💯 Thank you

2023-11-13 12:08 UTC, amiraabouhadid approved these changes

2023-11-13 12:11 UTC, merged