Formatting dao proposal's card
threefoldtech/tfgrid-sdk-ts pull request #1559
Opened 2023-12-03 13:46 UTC by maayarosama

### Description

Formatting dao proposals' cards.
![Screenshot from 2023-12-03 15-44-43](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/bfd9f613-cc39-4d9b-9cd4-d35e9a536fe2)

### Changes

- Made titles bold
- Changed view details link to a tooltip
- Added some styling to the card
### Related Issues

#1502
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-12-03 13:52 UTC, amiraabouhadid commented on packages/playground/src/dashboard/dao_view.vue
> +            <v-divider class="mt-1 mb-5 text-red-700" v-if="proposal.action" />
might be better to just wrap these two components in a div with a single v-if="proposal.action"

2023-12-04 11:40 UTC, amiraabouhadid commented
The details button should always be on the right even when there is no remark. Looks odd here, no?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/c42a7bbb-c84d-4641-89c5-524f338dabba)

2023-12-05 09:51 UTC, zaelgohary requested changes
Whenever I click on details, it redirects to the playground in a different tab as seen below.

[details_btn.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/6bdb3344-616d-4fb7-9670-dd35fd9165c2)

2023-12-10 14:05 UTC, maayarosama commented
> Whenever I click on details, it redirects to the playground in a different tab as seen below.
> 
>  details_btn.webm

As all proposals on devnet consists of summy data, the details button won't redirect to anything. However if you test against mainnet you can see that it redirects to the right link.

2023-12-10 14:17 UTC, zaelgohary commented
> > Whenever I click on details, it redirects to the playground in a different tab as seen below.
> > details_btn.webm
> 
> As all proposals on devnet consists of summy data, the details button won't redirect to anything. However if you test against mainnet you can see that it redirects to the right link.

Then the button should only be visible in mainnet only, no?
فا

2023-12-10 14:22 UTC, maayarosama commented
> > > Whenever I click on details, it redirects to the playground in a different tab as seen below.
> > > details_btn.webm
> > 
> > 
> > As all proposals on devnet consists of summy data, the details button won't redirect to anything. However if you test against mainnet you can see that it redirects to the right link.
> 
> Then the button should only be visible in mainnet only, no?

A per discussion with @AhmedHanafy725 it should be visible in all nets, The user who creates the proposal should always add accurate data.

2023-12-10 14:31 UTC, zaelgohary approved these changes

2023-12-10 14:32 UTC, merged