Development 313 fix stat cards
threefoldtech/tfgrid-sdk-ts pull request #1564
Opened 2023-12-03 18:57 UTC by amiraabouhadid

### Changes

- adjusted padding and margins of stat cards 

### Related Issues

 #1476

2023-12-04 13:33 UTC, amiraabouhadid commented
> build fails.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/287711922-bea0b622-dcfe-4139-8f71-735c343058d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTY3NzIsIm5iZiI6MTcwMTY5NjQ3MiwicGF0aCI6Ii80MDc3MDUwMS8yODc3MTE5MjItYmVhMGI2MjItZGNmZS00MTM5LThmNzEtNzM1YzM0MzA1OGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEzMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYjI3MWI1MTQ1OTU2MGVmNTM0M2NiZDFkMWI1NmMwYjUzMTJmZjExMWZjYWFkOGM1Y2I4MzkxYzgxMmQ0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4xqamWhM22-g8tDliZAm1Zj0f5MsFE1OgbWYzl8XqXQ)

Please run `yarn lerna run build`

2023-12-04 14:52 UTC, zaelgohary requested changes

2023-12-05 10:27 UTC, zaelgohary approved these changes

2023-12-05 12:16 UTC, AlaaElattar reviewed
- It looks like this for me 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f78a4fcd-319e-4883-bdda-e319e25f90a5)

- It looked normal only when i decreased the tab size.

2023-12-05 15:50 UTC, merged