Development 313 | contracts list tables
threefoldtech/tfgrid-sdk-ts pull request #1567
Opened 2023-12-04 07:47 UTC by Mahmoud-Emad

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-12-05 10:26 UTC, mohamedamer453 reviewed
- The rent contracts table is not expanded and doesn't show the contracts loading by default when you enter the contracts page.

   [Screencast from 05-12-23 11:48:25.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5fba4f58-5951-4ffc-9dc4-8f95f3c3a667)

- The `Delete` and `Export` buttons are missing.

- The total cost of contracts keeps loading forever.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fa9fa0c5-5630-4e32-adc1-f132d2bc2e07)

- In the total cost of contracts there's an id, i'm not sure what this id is for since it's not an id of an existing contract or my twin id so what is it?

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e2b54a83-b093-423a-8624-31e99944ebbc)

2023-12-05 10:26 UTC, mohamedamer453 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +    console.log(+onlyNumbers(contract.consumption));
Maybe remove the console logs if they're unnecessary

2023-12-05 10:26 UTC, mohamedamer453 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +    // totalCost.value = +new Decimal(totalCost.value).add(new Decimal(+));
Is this comment needed or should it be removed?

2023-12-10 10:57 UTC, mohamedamer453 reviewed
- Tables with data in them don't provide any indication that the data is being loaded when the refresh button is clicked, a good indicator would be having a loading spinner.

   [Screencast from 10-12-23 12:46:38.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1dc6d3d3-534a-46b1-af88-24ab5cd2012b)

2023-12-10 10:57 UTC, mohamedamer453 commented on packages/playground/src/components/contracts_list/contracts_table.vue
> +        <v-btn color="error" variant="tonal" @click="deletingDialog = false"> Cancel </v-btn>
Cancel button should be on the left side.

2023-12-10 10:57 UTC, mohamedamer453 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +// Import necessary types and libraries
This comment isn't needed since it's already clear what is happening here.

2023-12-10 10:57 UTC, mohamedamer453 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +// Define reactive variables
This comment isn't needed since it's already clear what is happening here.

2023-12-10 10:57 UTC, mohamedamer453 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +  // Initialize variables
This comment isn't needed since it's already clear what is happening here.

2023-12-11 12:55 UTC, mohamedamer453 reviewed
The total cost from the current contracts list is different from this one, i think the new one might be calculating the cost of node contracts only.

- Old contracts list.
 
   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6bf62b90-835c-49f3-b523-02f1960eba4f)

- New contracts list

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4d4a8eed-fc7d-4de2-82d8-6b685588feef)

2023-12-11 12:58 UTC, mohamedamer453 approved these changes

2023-12-12 08:32 UTC, AhmedHanafy725 commented
the total cost keeps loading forever


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/f45d9a15-e665-4860-9e10-2de7b6c6dbc9

2023-12-12 09:23 UTC, AhmedHanafy725 commented
while loading a name contract, this error happens on the console. why It tries to get the node id for this contract and we already know it's a name contract?


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/5599f6e8-a764-4f2d-b8b5-9360a072984a

2023-12-12 09:25 UTC, AhmedHanafy725 commented
this error happens while loading a node contract, do we call this method without sending the contract id?

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/ff96c399-9895-405b-9c26-904a67fa3fb2

2023-12-12 10:36 UTC, Mahmoud-Emad commented
> while loading a name contract, this error happens on the console. why It tries to get the node id for this contract and we already know it's a name contract?
> 
>  loading_name_contract.mp4

The issue was in the deployment dialog since we generated the Grafana URL from the contract -> node -> ID, and the name contract doesn't have nodeID, on it

2023-12-12 10:40 UTC, AhmedHanafy725 requested changes

2023-12-12 10:43 UTC, Mahmoud-Emad commented
> this error happens while loading a node contract, do we call this method without sending the contract id?
> 
>  loading_node_contract.mp4

The error here happened because we changed the `contractId` field to `contract_id` and the change not added in the data_dialog

2023-12-12 12:33 UTC, AhmedHanafy725 commented
can we disable the `export` button while deleting the contracts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/57efd7df-f45b-490f-b355-5a369acc1656)

2023-12-12 14:12 UTC, AhmedHanafy725 approved these changes

2023-12-12 14:12 UTC, merged