Add apply filters btn
threefoldtech/tfgrid-sdk-ts pull request #1832
Opened 2024-01-01 11:20 UTC by amiraabouhadid

### Description

Remove watchers on filters, add an apply button instead

### Changes

- remove watchers for filter inputs in nodes, farms & dedicated nodes
- add applyFilters function for button

### Related Issues

[#1775](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1775)

2024-01-01 12:01 UTC, ehab-hassan commented
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/c5d0a69f-4836-4683-bca7-ba562dfe16f8)
 - make 'clear' button at right and color="anchor"
 - apply color="secondary"
 - space between buttons maybe mr-2

2024-01-01 12:18 UTC, amiraabouhadid commented
> ![image](https://private-user-images.githubusercontent.com/10484295/293584137-c5d0a69f-4836-4683-bca7-ba562dfe16f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTEwMTYsIm5iZiI6MTcwNDExMDcxNiwicGF0aCI6Ii8xMDQ4NDI5NS8yOTM1ODQxMzctYzVkMGE2OWYtNDgzNi00NjgzLWJjYTctYmE1NjJkZmUxNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEyMDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNjg3ZTYxM2E3ODdiOGUwMmY0Mzc3NWNlZmM4M2I2NjcxZmI3MGRmMmE0MWZhZWQzODQ4MTQyMmY4OGU3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ak0iO1urYWnbncljPGpPNCH6hi6OYOxA0yZdb43IQ2Q)
> 
> * make 'clear' button at left and color="anchor"
> * Apply button color="secondary"
> * space between buttons maybe mr-2



> ![image](https://private-user-images.githubusercontent.com/10484295/293584137-c5d0a69f-4836-4683-bca7-ba562dfe16f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTEwMTYsIm5iZiI6MTcwNDExMDcxNiwicGF0aCI6Ii8xMDQ4NDI5NS8yOTM1ODQxMzctYzVkMGE2OWYtNDgzNi00NjgzLWJjYTctYmE1NjJkZmUxNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEyMDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNjg3ZTYxM2E3ODdiOGUwMmY0Mzc3NWNlZmM4M2I2NjcxZmI3MGRmMmE0MWZhZWQzODQ4MTQyMmY4OGU3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ak0iO1urYWnbncljPGpPNCH6hi6OYOxA0yZdb43IQ2Q)
> 
> * make 'clear' button at left and color="anchor"
> * Apply button color="secondary"
> * space between buttons maybe mr-2
applied 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/0babaa66-6b1b-47f3-9adc-a1cfab036f2b)

2024-01-01 12:32 UTC, ehab-hassan commented
@amiraabouhadid make clear button at left and apply at right

2024-01-01 12:35 UTC, amiraabouhadid commented
> @amiraabouhadid make clear button at left and apply at right

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/7cdfba44-b759-42cd-b9fc-276722d54a60)

2024-01-01 12:39 UTC, ehab-hassan commented
perfect thanks

2024-01-01 12:48 UTC, AlaaElattar commented
- I think the buttons will look better at the left. What do u think ?

2024-01-01 13:00 UTC, ehab-hassan commented
> > * I think the buttons will look better at the left. What do u think ?
> 
> ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/832491fd-da0b-4f99-801d-750e6bb83292)
> 

Agree100%

2024-01-01 13:07 UTC, AlaaElattar commented
- Here i chose offline nodes, then i wanted to filter on them.
- but the filters applied on all nodes not offline .

[Screencast from 01-01-2024 03:04:36 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/2c8af56d-7c83-4ae2-803f-b08e574435b6)

2024-01-02 07:40 UTC, AlaaElattar commented
- The initial value is `up` in the Nodes page, it should contain all nodes (up, down, and standby) 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/81855a1a-a4cf-4f85-afc9-7fc1b15db8ad)

2024-01-02 08:30 UTC, maayarosama commented
Initially the node status on nodes pages shouldn't be up, All nodes should be displayed

2024-01-02 09:32 UTC, AlaaElattar commented
- When i reset filters, I expect the nodes status to be reset also.

[Screencast from 01-02-2024 11:30:00 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/76034259-dcd3-4734-893d-83b1dbae5f05)

2024-01-02 10:32 UTC, AlaaElattar approved these changes
works fine

2024-01-02 11:13 UTC, 0oM4R requested changes

2024-01-02 11:13 UTC, 0oM4R commented on packages/playground/src/components/filter.vue
> +                :loading="loading"
i think we need to set it to disabled not loading
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4f6d86f0-2b86-40e6-9e9d-6a64e81cfb19)

2024-01-02 11:13 UTC, 0oM4R commented on packages/playground/src/views/nodes.vue
>      const request = debounce(_requestNodes, 1000);
i think there is no need for the denounce now

2024-01-02 11:14 UTC, 0oM4R commented on packages/playground/src/views/nodes.vue
> +      // filterOptions.value = optionsInitializer();
please remove the comment if it is not needed

2024-01-02 12:04 UTC, 0oM4R commented
clear btn is still loading please check it out

2024-01-02 12:25 UTC, 0oM4R commented
please check network on each click will send 2 requests
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0c1798c7-6597-4e59-9ae3-a27eef54c828)

2024-01-02 12:29 UTC, AlaaElattar commented
- clear button shouldn't be enabled until user starts to filter 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/68749161-ed80-463c-9a99-6c340e2f51f3)

2024-01-02 12:33 UTC, mohamedamer453 reviewed
- At small window sizes the Apply button exceeds the bounds of the filters box.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/711d6225-5fed-4c7c-8fc7-f5122468c353)

2024-01-02 13:19 UTC, AlaaElattar commented
- when i filter after choosing node status, the node status is cleared. 

[Screencast from 01-02-2024 03:16:18 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/55556d99-96f5-4dd6-82cb-b384b5ac3382)

2024-01-03 06:33 UTC, AlaaElattar approved these changes
Great Job

2024-01-03 07:48 UTC, Mahmoud-Emad commented
When enabling the GPU or Gateway options and then pressing on apply button, the switches go back to being false

[Screencast from 01-03-2024 09:45:50 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/e1713af4-efa6-4148-8165-748bed06f415)

2024-01-03 07:52 UTC, Mahmoud-Emad commented
The GPU option in the Dedicated Nodes screen doesn't work as expected.

[Screencast from 01-03-2024 09:50:24 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ccd18b0c-39a3-4995-a438-d725c17246fc)

2024-01-03 07:58 UTC, Mahmoud-Emad commented
When filtering with values e.g. Node ID, when I want to display all of the nodes the button of `Apply` gets disabled and I can't go back.

[Screencast from 01-03-2024 09:54:53 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b586e95e-2c1d-453f-aedb-3cb2b50e92fa)

2024-01-03 10:58 UTC, Mahmoud-Emad commented
> The GPU option in the Dedicated Nodes screen doesn't work as expected.
> 
>  Screencast.from.01-03-2024.09.50.24.AM.webm 
> No GPU card on the node 148 as seen in the screen
> 
> ![image](https://private-user-images.githubusercontent.com/57001890/293858828-596aa226-1ed5-483b-93ad-22d97d29fd82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzkwNDIsIm5iZiI6MTcwNDI3ODc0MiwicGF0aCI6Ii81NzAwMTg5MC8yOTM4NTg4MjgtNTk2YWEyMjYtMWVkNS00ODNiLTkzYWQtMjJkOTdkMjlmZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwNDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMmQ1NDI2YzgxNTA5Yjc4M2NhZTE5YmFmYTQyODYwNzYxZWI1MjBlMjAyYzI4M2EyMGRlZjUyMjMwNzg0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-DTF6M55xvrLSatJtBzH2sAbX7y-qjvPn86eFpHaME)

The resolution of this comment introduces a new concern. The existing functionality for the grid proxy's GPU filter is set to "True," indicating a requirement for GPU, while "False" signifies the absence of this requirement. Consequently, when the switch is set to "False," it implies the necessity to filter all nodes with GPU filter set to "False." Consequently, nodes without GPUs will not be returned. 

Refer to the [Screencast from 01-03-2024 12:51:37 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/993e36dd-933b-4202-9466-e8cc4d7258b6) for more clarity.

To address this issue, you have two potential solutions:
1. Rectify the situation in the grid proxy.
2. Resolve it by substituting the "False" keyword with "undefined" :D

2024-01-03 12:00 UTC, MohamedElmdary approved these changes

2024-01-03 12:01 UTC, merged