Improve node selector details
threefoldtech/tfgrid-sdk-ts pull request #1884
Opened 2024-01-04 13:14 UTC by MohamedElmdary

### Description
Improve node selector details

### Changes
- redesign node card
- write a selectable table (custom component) to work as VSelect

### Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1872

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-01-04 13:41 UTC, AlaaElattar commented
i think the separator between cards should be stronger to be clear. what do u think ?

2024-01-04 14:01 UTC, MohamedElmdary commented
> i think the separator between cards should be stronger to be clear. what do u think ?

VDivider style doesn't match with outer border so I added a border bottom instead

2024-01-04 19:00 UTC, xmonader requested changes
Let's not show a serial if it's default string

2024-01-08 14:32 UTC, AhmedHanafy725 reviewed
what does it mean the shared chip on the farm? I prefer to have farm name instead.

2024-01-08 15:04 UTC, mohamedamer453 reviewed
- After the nodes are loaded it randomly scrolls to one of the nodes, i think it should load the nodes and leave it up to the user to select the desired node.

[Screencast from 08-01-24 15:54:16.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d35033ab-e0e5-452d-8996-aafac77be7b6)

- I believe as it was agreed upon before that the user doesn't need to know anything about the term storage pools and it would be better if the message was updated to something else like "checking if the deployment will fit in the node's disks" or something similar.

  ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/86d62afa-bb47-43fe-bb44-06d3e621b404)


- IMO it would look better if the node id was written in the same way as the farm id. e.g. "Node ID: 11" instead of using brackets.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b02f7f66-ccd0-4bf9-987c-eb2b8507963c)

- In the manual filter, when the dedicated node filter is enabled and a shared node id is added it should mention that this node is shared in the error message instead of mentioning that this node is not rented.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/51e289e5-e5f7-4ba7-889c-a7cb985d4209)

- On mainnet, some nodes appeared without flag. e.g. node 2336

 ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/bf9657ef-286f-4600-90b0-38efa6cf88c1)

even though the node has a country in its details from the gridproxy

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/93cf71c7-250a-40ed-b7e4-a9299ba182c3)

- After Loading more nodes the storage pools check is done even when the same node is selected.

   [Screencast from 08-01-24 16:40:48.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/af3951f8-a3b2-400f-b590-c5a6769a1fdd)

2024-01-09 08:15 UTC, MohamedElmdary commented
> what does it mean the shared chip on the farm? I prefer to have farm name instead.

For farmName we need extra request

2024-01-09 09:17 UTC, MohamedElmdary commented
> * After the nodes are loaded it randomly scrolls to one of the nodes, i think it should load the nodes and leave it up to the user to select the desired node.

It was a requested feature to improve ux

2024-01-09 12:32 UTC, mohamedamer453 commented
> * After Loading more nodes the storage pools check is done even when the same node is selected.
>   

This issue is still present

2024-01-09 14:31 UTC, MohamedElmdary commented
> > * After Loading more nodes the storage pools check is done even when the same node is selected.
> 
> This issue is still present


It's verify that node still valid

2024-01-09 15:49 UTC, mohamedamer453 commented on packages/playground/src/components/node_selector/TfAutoNodeSelector.vue
> +              <!-- <div class="border-b" :style="{ borderBottomWidth: '2px !important' }" /> -->
remove the commented line

2024-01-09 15:50 UTC, mohamedamer453 approved these changes

2024-01-10 08:30 UTC, 0oM4R approved these changes

2024-01-10 08:34 UTC, xmonader approved these changes

2024-01-10 08:35 UTC, merged