Edit manual links
threefoldtech/tfgrid-sdk-ts pull request #201
Opened 2023-04-30 12:21 UTC by zaelgohary

### Description

edit manual links

### Changes

- edit manual links in playground

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/79

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2023-04-30 12:30 UTC, AhmedHanafy725 requested changes

2023-04-30 12:30 UTC, AhmedHanafy725 commented on packages/weblets/src/elements/ContractsList/ContractsList.wc.svelte
> +    <a target="_blank" href="https://manual.grid.tf/tfchain/tfchain_external_service_contract.html?highlight=contract%20list#create-service-contract">
I think this link can't be a replacement for the old one

2023-04-30 12:30 UTC, AhmedHanafy725 commented on packages/weblets/src/elements/caprover/Caprover.wc.svelte
> +        <a target="_blank" href="https://manual.grid.tf/weblets/weblets_caprover.html">
I think this should be `https://manual.grid.tf/weblets/weblets_caprover_worker.html`

2023-04-30 13:02 UTC, zaelgohary commented
TFhub validator & Dashboard links were missing so, I created an [issue](https://github.com/threefoldtech/info_grid/issues/73)

2023-05-17 07:44 UTC, AhmedHanafy725 approved these changes

2023-05-17 07:53 UTC, merged