Add health column
threefoldtech/tfgrid-sdk-ts pull request #2120
Opened 2024-02-04 10:09 UTC by samaradel

### Description

Add ```Health``` column to display node status and tooltip for ```message``` in case ```error```

### Changes

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/1def59d1-3b18-494d-a93c-10b7f778bbcd)

### Related Issues

- [#2104](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2104)
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-02-04 10:52 UTC, zaelgohary commented
Can we change the chip color? Check status or type chips in node finder.

2024-02-04 10:57 UTC, Mahmoud-Emad requested changes
Good job ya Samar, one small comment :)

2024-02-04 10:57 UTC, Mahmoud-Emad commented on packages/playground/src/components/vm_deployment_table.vue
> +          <v-tooltip v-if="item.columns.status == 'error'" activator="parent" location="top">{{
```suggestion
          <v-tooltip v-if="item.columns.status == NodeHealth.error" activator="parent" location="top">{{
```

2024-02-04 11:01 UTC, zaelgohary commented on packages/playground/src/utils/get_nodes.ts
> +    return { color: "success", type: NodeHealth.Ok };
```suggestion
    return { color: "primary", type: NodeHealth.Ok };
```

2024-02-04 11:04 UTC, samaradel commented on packages/playground/src/utils/get_nodes.ts
> +}
I agree, I thought it's different

2024-02-04 11:45 UTC, samaradel commented on packages/playground/src/utils/get_nodes.ts
> +}
@AhmedHanafy725 can you check please.

2024-02-04 12:11 UTC, ehab-hassan commented
@samaradel can we make it the same style of success status 

mean text-success and tonal background

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d42cc04c-71dd-43a7-a6f0-ab13ad2008a3)

2024-02-05 10:02 UTC, mohamedamer453 reviewed
- Health column is missing in the kubernetes deployment list.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e13aebb4-4c18-42ec-b68a-62fae8433f5b)

2024-02-05 14:52 UTC, samaradel commented
> * Health column is missing in the kubernetes deployment list.
>   ![image](https://private-user-images.githubusercontent.com/101194226/302246723-e13aebb4-4c18-42ec-b68a-62fae8433f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDMwODQsIm5iZiI6MTcwNzE0Mjc4NCwicGF0aCI6Ii8xMDExOTQyMjYvMzAyMjQ2NzIzLWUxM2FlYmI0LTRjMTgtNDJlYy1iNjhhLTYyZmFlODQzM2Y1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNDE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2VmOTE4ZWFiMTMzYmVjNTZiOGFhYWQzZTQ2YWYwY2Q2ZWRiNzcxNTk3YjdiNjdkOWQyMzNkMmIxMDk1YzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EnBjnS5SivG8RDYxqeD1vWh6vTzLsV9Vzf0-EhwkyPA)

will add it there too

2024-02-06 10:16 UTC, samaradel commented
> * Health column is missing in the kubernetes deployment list.
>   ![image](https://private-user-images.githubusercontent.com/101194226/302246723-e13aebb4-4c18-42ec-b68a-62fae8433f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDMwODQsIm5iZiI6MTcwNzE0Mjc4NCwicGF0aCI6Ii8xMDExOTQyMjYvMzAyMjQ2NzIzLWUxM2FlYmI0LTRjMTgtNDJlYy1iNjhhLTYyZmFlODQzM2Y1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNDE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2VmOTE4ZWFiMTMzYmVjNTZiOGFhYWQzZTQ2YWYwY2Q2ZWRiNzcxNTk3YjdiNjdkOWQyMzNkMmIxMDk1YzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EnBjnS5SivG8RDYxqeD1vWh6vTzLsV9Vzf0-EhwkyPA)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/0bde7f95-1ee9-4025-9b6c-ed43ba5d6143)
 added

2024-02-06 14:30 UTC, mohamedamer453 reviewed
On error there's a tooltip but the value of the tooltip is empty.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/137835c8-05df-4f7f-ab31-083deb6cbdc4)

Even when there's an error message present in the JSON details.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ae5f3a9a-0ede-4781-9e4e-04016402099a)

2024-02-06 15:23 UTC, samaradel commented
> On error there's a tooltip but the value of the tooltip is empty.
> 
> ![image](https://private-user-images.githubusercontent.com/101194226/302663005-137835c8-05df-4f7f-ab31-083deb6cbdc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzMyNjMsIm5iZiI6MTcwNzIzMjk2MywicGF0aCI6Ii8xMDExOTQyMjYvMzAyNjYzMDA1LTEzNzgzNWM4LTA1ZGYtNGY3Zi1hYjMxLTA4M2RlYjZjYmRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxNTIyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODFmMTc5ZTc5MWVkNmIxOTE3ZTkzNDZlZjgzOWFlZmFkMTFhZTFhZWZjNmU2MzAzZTljZGNlZjdlNzAzMTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JlPZLMu0ABgMxDBFnRgpSSNfRbo8UKi3Ki68vnDXe1U)
> 
> Even when there's an error message present in the JSON details.
> 
> ![image](https://private-user-images.githubusercontent.com/101194226/302663708-ae5f3a9a-0ede-4781-9e4e-04016402099a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzMyNjMsIm5iZiI6MTcwNzIzMjk2MywicGF0aCI6Ii8xMDExOTQyMjYvMzAyNjYzNzA4LWFlNWYzYTlhLTBlZGUtNDc4MS05ZTRlLTA0MDE2NDAyMDk5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxNTIyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWQ2MjU3MGYwODdkOTVjYzE5NTczMzhhMGYxMDA1OTUxMjU0MGVhNWQ2ZGNjZGRkMWQzNzA3ZjA4OTUzOTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cS6O9jGj23iezpT0hT6DIPIxU-RWOH11sqkZD41-6Xc)

fixed

2024-02-07 09:04 UTC, mohamedamer453 approved these changes
Working fine now for both cases.

Health is ok
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/12486919-0480-4d32-86ca-0126a90f4075)

There's an error, and in case of an error a tooltip with the error message appears.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fd29ef94-4d1c-43a5-ba5e-8f29503c355e)

2024-02-07 09:39 UTC, ehab-hassan approved these changes

2024-02-07 11:00 UTC, Mahmoud-Emad approved these changes

2024-02-07 11:04 UTC, merged