add stats summary endpoint
threefoldtech/tfgrid-sdk-ts pull request #2123
Opened 2024-02-05 10:17 UTC by 0oM4R

### Description

Using nginx javascript we can run a script whenever the user hit the target endpoint, the mentioned endpoint is `/api/stats-summary`, this will reduce code replication and make data consistent over different websites; threefold.io, dashboard 
also we are caching the data for one day, if any errors happen while updating it, we are returning the outdated data with flag `outdated` if there is no cached data too or if any error happen while reading it, we return a dummy data,
### Changes

- DockerFile: 
   - update the nginx version: njs require the latest nginx image
   - copy nginx files to the image
- Nginx : 
   - in nginx.conf I just loaded the needed js module and  set the resolver:
     the actual changes on the default nginx.conf is :
      ```
     load_module modules/ngx_http_js_module.so;
      js_path "/etc/nginx/njs/";
  
      resolver 8.8.8.8;
      js_import main from stats.js;
     ```
   - add `/summary` endpoint to server in `default.conf
   - add njs script

### Related Issues

 - #1981 

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-02-05 10:46 UTC, 0oM4R commented
the verify option is disabled here as we <currently> don't have ssl cert for the image;
![Screenshot from 2024-02-05 12-41-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/f0d2c84c-4a7a-411e-abbf-80852f2557ee)

 https://github.com/threefoldtech/tfgrid-sdk-ts/blob/0e5faac8d2d3c49ffcf907240ed0905ae486791c/packages/new_stats/nginx/njs/stats.js#L15

2024-02-05 10:49 UTC, MohamedElmdary commented
Do we need to implement retries 3 times and/or return back default values if it failed? @AhmedHanafy725

2024-02-06 08:13 UTC, MohamedElmdary commented
1. [ ] Let's invest if this script is used as server or just fire whenever we call route ... in case it works as server we can implement a very simple in-memory cache (last for 1 day)

2. [ ] Add 3 reties for request (better to call the failed urls only `if possible`)

2024-02-11 09:41 UTC, AhmedHanafy725 requested changes

2024-02-11 14:27 UTC, AhmedHanafy725 approved these changes

2024-02-11 14:36 UTC, MohamedElmdary approved these changes

2024-02-12 09:13 UTC, merged