Trigger Minting hash validation before clicking view
threefoldtech/tfgrid-sdk-ts pull request #2207
Opened 2024-02-19 12:14 UTC by AlaaElattar

### Description

The validation for minting should be initiated before clicking the view button.

Not only should the validation check the hash's length, but also if the hash is valid or not.
### Changes

- Make all validations done before clicking view.
- Found that if hash valid will appear automatically, then there's no need for view button.
### Related Issues

#1848 

[Screencast from 02-19-2024 02:01:36 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/2c401fe4-d4a0-4cc0-8bb0-944bed67d2bd)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-02-19 13:27 UTC, 0oM4R requested changes
I think one of the two error msgs here will be better 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0102e903-eae0-4071-a439-fede654e99fc)

2024-02-19 13:31 UTC, 0oM4R requested changes

2024-02-19 13:32 UTC, 0oM4R commented on packages/playground/src/views/minting_view.vue
> +);
we can move this to the component 
`@update:model-value="reset"`

2024-02-19 14:06 UTC, 0oM4R approved these changes
great work thanks ya Alaa

2024-02-20 08:52 UTC, amiraabouhadid approved these changes

2024-02-20 08:52 UTC, merged