adding mycelium flag
threefoldtech/tfgrid-sdk-ts pull request #2238
Opened 2024-02-25 12:10 UTC by khaledyoussef24

### Description

#1841 

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-02-25 12:11 UTC, khaledyoussef24 commented
@AlaaElattar  created this branch instead of the other one.
could not resolve all the conflicts so created this one.

2024-04-15 09:17 UTC, Mahmoud-Emad commented
@A-Harby Can you please give it a look?

2024-04-15 11:57 UTC, zaelgohary requested changes

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/casperlabs.ts
> +  // await grid3.disconnect();
The connection hangs as this line is commented.

```suggestion
  await grid3.disconnect();
```

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/discourse.ts
> +  await getDeployment(grid3, vms.name);
I get the following error while running the discourse script.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/726f33dc-3e1d-452d-ad37-69769c779f9b)

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/discourse.ts
> +  await getDeployment(grid3, vms.name);
Also, the script should not have continued if an error happened while deploying.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/funkwhale.ts
> +  await getDeployment(grid3, vms.name);
Same happens here as discourse.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/nodepilot.ts
> +  // await deploy(grid3, vms);
Should be uncommented.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/owncloud.ts
> +    log(`You can access OwnCloud via the browser using: http://captain.${res[0].env.CAPROVER_ROOT_DOMAIN}`);
I got undefined.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/d5fc4414-1744-44be-a48d-04cf32f94140)

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/peertube.ts
> +    log(`You can access peertube via the browser using: http://newVMS5.${res[0].env.PEERTUBE_WEBSERVER_HOSTNAME}`);
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e2aeca4e-5aa7-4e18-bf42-457f6b5f0e3d)

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/presearch.ts
> +  // await deploy(grid3, vms);
Should be uncommented.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/presearch.ts
> +  // await getDeployment(grid3, vms.name);
Same here.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/subsquid.ts
> +  // await deploy(grid3, vms);
Should be uncommented.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/umbrel.ts
> +  // await deploy(grid3, vms);
Should be uncommented.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/wordpress.ts
> +    log(`You can access umbrel via the browser using: http://newVMS5.${res[0].env.UMBREL_WEBSERVER_HOSTNAME}`);
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/6e87a465-b82f-48dd-90b1-20fb4dc43c35)

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/umbrel.ts
> +  // await getDeployment(grid3, vms.name);
Same here.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/umbrel.ts
> +  await cancel(grid3, { name: vms.name });
Should be commented.

2024-04-15 11:57 UTC, zaelgohary commented on packages/grid_client/scripts/nodepilot.ts
> +        mycelium: true,
I'm not sure if Nodepilot should have a mycelium network.

2024-04-15 12:08 UTC, zaelgohary reviewed
I tried running the tests using 'yarn workspace @threefold/grid_client test --runInBand' as explained in the docs but all tests failed as shown below.
```
yarn workspace v1.22.19
yarn run v1.22.19
$ jest --runInBand
 FAIL  tests/modules/zdb.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/zdb.test.ts:4:1)

 FAIL  tests/modules/wordpress.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/wordpress.test.ts:2:1)

 FAIL  tests/modules/vm.test.ts
  ● Test suite failed to run

    tests/modules/vm.test.ts:90:7 - error TS2741: Property 'mycelium' is missing in type '{ name: string; node_id: any; cpu: number; memory: number; rootfs_size: number; disks: any[]; flist: string; entrypoint: string; public_ip: false; planetary: true; env: { SSH_KEY: any; Test_KEY: string; }; solutionProviderId: null; }' but required in type 'MachineModel'.

     90       {
              ~
     91         name: vmName,
        ~~~~~~~~~~~~~~~~~~~~~
    ... 
    105         solutionProviderId: null,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    106       },
        ~~~~~~~

      src/modules/models.ts:111:26
        111   @Expose() @IsBoolean() mycelium: boolean;
                                     ~~~~~~~~
        'mycelium' is declared here.
    tests/modules/vm.test.ts:258:7 - error TS2741: Property 'mycelium' is missing in type '{ name: string; node_id: any; cpu: number; memory: number; rootfs_size: number; disks: { name: string; size: number; mountpoint: string; }[]; flist: string; entrypoint: string; public_ip: false; planetary: true; env: { ...; }; solutionProviderId: null; }' but required in type 'MachineModel'.

    258       {
              ~
    259         name: vmName,
        ~~~~~~~~~~~~~~~~~~~~~
    ... 
    279         solutionProviderId: null,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    280       },
        ~~~~~~~

      src/modules/models.ts:111:26
        111   @Expose() @IsBoolean() mycelium: boolean;
                                     ~~~~~~~~
        'mycelium' is declared here.
    tests/modules/vm.test.ts:437:9 - error TS2741: Property 'mycelium' is missing in type '{ name: string; node_id: any; cpu: number; memory: number; rootfs_size: number; disks: any[]; flist: string; entrypoint: string; public_ip: false; planetary: true; env: { SSH_KEY: any; TEST_KEY: string; }; }' but required in type 'MachineModel'.

    437   const vm1: MachineModel = {
                ~~~

      src/modules/models.ts:111:26
        111   @Expose() @IsBoolean() mycelium: boolean;
                                     ~~~~~~~~
        'mycelium' is declared here.
    tests/modules/vm.test.ts:454:9 - error TS2741: Property 'mycelium' is missing in type '{ name: string; node_id: any; cpu: number; memory: number; rootfs_size: number; disks: any[]; flist: string; entrypoint: string; public_ip: false; planetary: true; env: { SSH_KEY: any; TEST_KEY: string; }; }' but required in type 'MachineModel'.

    454   const vm2: MachineModel = {
                ~~~

      src/modules/models.ts:111:26
        111   @Expose() @IsBoolean() mycelium: boolean;
                                     ~~~~~~~~
        'mycelium' is declared here.

 FAIL  tests/modules/umbrel.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/umbrel.test.ts:2:1)

 FAIL  tests/modules/tfchain.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/tfchain.test.ts:9:1)

 FAIL  tests/modules/taiga.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/taiga.test.ts:2:1)

 FAIL  tests/modules/subsquid.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/subsquid.test.ts:2:1)

 FAIL  tests/modules/stellar.test.ts
  ● Test suite failed to run

    EACCES: permission denied, open '/home/zainab/.ssh/id_ed25519.pub'

      10 | const mnemonic = env.MNEMONIC;
      11 | const storeSecret = env.STORE_SECRET;
    > 12 | const ssh_key = fs.readFileSync(os.homedir() + "/.ssh/id_ed25519.pub", "utf-8");
         |                    ^
      13 | let config;
      14 |
      15 | if (!network || !mnemonic || !ssh_key) {

      at Object.<anonymous> (tests/client_loader.ts:12:20)
      at Object.<anonymous> (tests/modules/stellar.test.ts:8:1)

 FAIL  tests/modules/qsfs.test.ts
  ● Test suite failed to run

    tests/modules/qsfs.test.ts:187:7 - error TS2741: Property 'mycelium' is missing in type '{ name: string; node_id: any; cpu: number; memory: number; rootfs_size: number; disks: any[]; flist: string; entrypoint: string; public_ip: false; planetary: true; qsfs_disks: { qsfs_zdbs_name: string; ... 6 more ...; mountpoint: string; }[]; env: { ...; }; solutionProviderId: null; }' but required in type 'MachineModel'.

    187       {
              ~
    188         name: vmName,
        ~~~~~~~~~~~~~~~~~~~~~
    ... 
    214         solutionProviderId: null,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    215       },
        ~~~~~~~

      src/modules/models.ts:111:26
        111   @Expose() @IsBoolean() mycelium: boolean;
                                     ~~~~~~~~
        'mycelium' is declared here.
    tests/modules/qsfs.test.ts:527:7 - error TS2741: Property 'mycelium' is missing in type '{ name: string; node_id: any; cpu: number; memory: number; rootfs_size: number; disk_size: number; public_ip: false; public_ip6: f [...]

2024-04-15 12:20 UTC, khaledyoussef24 commented
@zaelgohary I will check for it and make sure that also docs is fine.

2024-05-01 06:44 UTC, Mahmoud-Emad commented
@khaledyoussef24 
If you still working on it, please draft it :)

2024-05-07 14:49 UTC, khaledyoussef24 commented
will delete this branch and make 2 other prs one for solution scripts and the other for test modules

2024-05-19 09:48 UTC, closed without merging