Remove Old Dashboard, Stats, Weblets & their workflows
threefoldtech/tfgrid-sdk-ts pull request #2436
Opened 2024-03-14 12:35 UTC by zaelgohary

### Description

Remove Old Dashboard, Stats, Weblets & their workflows

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1811

### Documentation PR

For UI changes, Plaese provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-03-18 13:46 UTC, AlaaElattar commented
- please resolve conflicts

2024-03-18 20:06 UTC, AhmedHanafy725 requested changes
- Remove the packages links from the main [readme](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development_314_remove_unused_packages/README.md)
- Remove the paths related to these packages from [eslint config](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/.eslintrc.json)
- Run yarn install to remove all the dependencies related to them.

2024-03-19 10:30 UTC, AhmedHanafy725 approved these changes

2024-03-19 10:45 UTC, 0oM4R approved these changes

2024-03-19 10:56 UTC, merged