Activate mnemonic even if it doesn't have a twin id
threefoldtech/tfgrid-sdk-ts pull request #2506
Opened 2024-03-27 19:30 UTC by samaradel

### Description

- Remove Activation account button
- Trigger the activation while connecting the wallet

### Changes

[Screencast from 27-03-24 21:18:00.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/4b691e4f-2133-4b1c-9990-b241f37d9080)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2350

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-03-31 09:53 UTC, amiraabouhadid requested changes
I get this error when I enter the mnemonics of an account that hasnt been activated yet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/a0fe692f-4761-4c64-af53-0d33ff6c9f53)

2024-04-02 11:05 UTC, samaradel commented
@amiraabouhadid It's deactivated when click connect

2024-04-02 22:42 UTC, samaradel commented
@amiraabouhadid error fixed

2024-04-03 13:18 UTC, zaelgohary reviewed
Although email is required while activation, it's not in the metadata in the twin details page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/ff352f9c-60ea-4a30-ac68-3f40610d9525)

2024-04-04 13:59 UTC, samaradel commented
@zaelgohary fixed

2024-04-04 14:16 UTC, zaelgohary commented on packages/playground/src/weblets/profile_manager.vue
> +      isValid.value = true;
What does this boolean do? Same for the one outside the condition.

2024-04-07 03:12 UTC, amiraabouhadid approved these changes

2024-04-07 03:12 UTC, merged