Edit subdomain char limit
threefoldtech/tfgrid-sdk-ts pull request #2573
Opened 2024-04-16 15:13 UTC by zaelgohary

### Changes

- Remove twin ID & solution name from subdomain
- Limit initial subdomain value to 5 chars

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/29398de8-73cc-4210-9235-5b954c37f9bd)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2564

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-04-17 10:49 UTC, MohamedElmdary commented
Shouldn't we keep deployment as before with oldPrefix ?

2024-04-30 12:55 UTC, AhmedHanafy725 requested changes

2024-04-30 12:55 UTC, AhmedHanafy725 commented on packages/playground/src/utils/validators.ts
> +  console.log({ valid });
please remove the debug logs

2024-04-30 12:55 UTC, AhmedHanafy725 commented on packages/playground/src/utils/validators.ts
> +    return { message: "Subdomain  already exists." };
```suggestion
    return { message: "Subdomain is already taken." };
```

2024-05-01 05:52 UTC, zaelgohary commented on packages/playground/src/components/manage_gateway_dialog.vue
> +                  subdomain => validators.maxLength('Subdomain cannot exceed 15 characters.', 15)(subdomain),
I had to change the limit as the validation for name in get_name_contract is 15 chars max. so, I either loosen the validation from the Dashboard or the Grid Client.

2024-05-02 06:10 UTC, Mahmoud-Emad commented on packages/playground/src/components/manage_gateway_dialog.vue
> +                  subdomain => validators.maxLength('Subdomain cannot exceed 15 characters.', 15)(subdomain),
Hello, What is the status here? :)

2024-05-02 06:39 UTC, AhmedHanafy725 commented on packages/playground/src/components/manage_gateway_dialog.vue
> +                  subdomain => validators.maxLength('Subdomain cannot exceed 15 characters.', 15)(subdomain),
please change it in the grid client

2024-05-02 14:04 UTC, AhmedHanafy725 commented on packages/grid_client/src/modules/models.ts
> +  @Expose() @IsString() @IsNotEmpty() @IsAlphanumeric() @MaxLength(30) name: string;
to be like the gateways model make it `NameLength + 20`

2024-05-08 12:02 UTC, MohamedElmdary approved these changes

2024-05-08 12:56 UTC, samaradel approved these changes

2024-05-08 14:10 UTC, merged