Fix vuetify table
threefoldtech/tfgrid-sdk-ts pull request #2712
Opened 2024-05-16 12:59 UTC by MohamedElmdary

### Description
Vuetify table headers

### Changes
- fix: vuetify table headers

### Related Issues
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2711

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-05-19 07:56 UTC, Mahmoud-Emad requested changes

2024-05-19 07:56 UTC, Mahmoud-Emad commented on packages/playground/src/views/farms.vue
> +  // { title: "Available IPs", key: "freePublicIp", sortable: false },
let's remove the commented code if not needed

2024-05-27 08:21 UTC, maayarosama approved these changes

2024-05-28 11:39 UTC, Mahmoud-Emad approved these changes
Go ahead!

2024-05-28 11:40 UTC, merged