Adding a batchSize and applying extrinsics per batch
threefoldtech/tfgrid-sdk-ts pull request #2728
Opened 2024-05-19 15:31 UTC by maayarosama

### Description

Adding a batch size to batchCancelContracts method. so instead of canceling all contracts at once, they get canceled in batches 
### Changes

- Adding a batch size and applyAllExtrinsics per batch
### Related Issues

- #2485

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-05-20 07:38 UTC, AhmedHanafy725 requested changes
This should be applied to all extrinsic methods not only canceling contracts. I suggest it to be done in utility methods (batch, batchAll) [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/tfchain_client/src/utility.ts)

2024-05-26 12:39 UTC, MohamedElmdary commented on packages/grid_client/src/clients/tf-grid/contracts.ts
> +
@maayarosama  remove this file as it got no changes

2024-05-27 09:17 UTC, AhmedHanafy725 requested changes

2024-05-27 09:17 UTC, AhmedHanafy725 commented on packages/tfchain_client/src/utility.ts
> +const batchSize = 400;
constants should be uppercase
```suggestion
const BATCH_SIZE = 400;

```

2024-05-27 09:17 UTC, AhmedHanafy725 commented on packages/tfchain_client/src/utility.ts
> +        result.concat(res);
we should overwrite the variable again as `concat` returns the concatenation result and doesn't change the list.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/4f9817ff-5b22-4099-a6bd-c4eeb2ca5776)

```suggestion
        result = result.concat(res);

```

2024-05-27 12:59 UTC, AhmedHanafy725 approved these changes

2024-05-27 13:16 UTC, amiraabouhadid approved these changes

2024-05-27 13:17 UTC, merged