Add ipv6 to filters in Node Finder
threefoldtech/tfgrid-sdk-ts pull request #2738
Opened 2024-05-20 14:39 UTC by zaelgohary

### Description

- Add ipv6 to filters in node finder

[ipv6.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/74c93741-94c7-44cc-b431-08442c460d40)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/155

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-05-20 14:51 UTC, AhmedHanafy725 requested changes
there is a switch for ipv6 while deploying any solution, but this switch doesn't filter the nodes as it wasn't supported. please make sure it filter the nodes there too.

2024-05-26 14:03 UTC, zaelgohary commented
> IPv6 filter doesn't work in micro VM 

I was using a wrong filter query. It should've be ipv6 only as seen below. Should be fixed now. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/3d1dc798-7d59-453f-aeda-ca30530c8d51)

2024-05-26 15:04 UTC, MohamedElmdary approved these changes

2024-05-27 07:12 UTC, maayarosama approved these changes

2024-05-27 09:09 UTC, AhmedHanafy725 requested changes
I have opened an issue for supporting this query on farms too to show only the farms that have ipv6 in case it was selected

2024-05-27 09:32 UTC, zaelgohary commented on packages/grid_client/src/primitives/nodes.ts
> +      ipv6: options.hasIPv6,
Yes, you're right but this is how it's done in Grid Proxy as explained [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2738#issuecomment-2132234885). Should I open an issue in the Grid proxy to change the query param to has_ipv6?

2024-05-27 10:14 UTC, zaelgohary commented on packages/grid_client/src/primitives/nodes.ts
> +      ipv6: options.hasIPv6,
The swagger wasn't updated. I added the filter to proxy and updated both grid client & playground.

2024-05-28 08:20 UTC, maayarosama approved these changes

2024-06-09 11:29 UTC, AhmedHanafy725 approved these changes

2024-06-09 12:49 UTC, merged