Edit additional fee err msg
threefoldtech/tfgrid-sdk-ts pull request #2970
Opened 2024-06-12 12:25 UTC by zaelgohary

### Description

- Edit err msg if node has active contract

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2937

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-06-12 14:39 UTC, samaradel approved these changes

2024-06-13 05:51 UTC, Mahmoud-Emad requested changes
Good job ya Zainab :)

2024-06-13 05:51 UTC, Mahmoud-Emad commented on packages/playground/src/dashboard/components/set_extra_fee.vue
> +        if (e instanceof TFChainErrors.smartContractModule.NodeHasActiveContracts) msg += " Node has acive contracts.";
```suggestion
        if (e instanceof TFChainErrors.smartContractModule.NodeHasActiveContracts) msg += " Node has active contracts.";
```

2024-06-13 07:11 UTC, maayarosama approved these changes

2024-06-13 08:49 UTC, Mahmoud-Emad approved these changes

2024-06-13 08:49 UTC, merged