Node statistics UI
threefoldtech/tfgrid-sdk-ts pull request #2989
Opened 2024-06-13 14:38 UTC by samaradel

### Description

- Center all items vertically
- Remove vertical divider

### Changes

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/b7cd8f45-336e-42a6-b3b2-bdbc275d25ca)
### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2897
### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-06-19 06:59 UTC, amiraabouhadid requested changes
please fix spacing between cards
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/e77b4e94-f2ea-4274-84bf-e1d4c437fdd7)

2024-06-23 06:05 UTC, Mahmoud-Emad approved these changes

2024-06-23 06:27 UTC, zaelgohary requested changes
The issue requested the last card to take up the whole space if it's the only card in the row.

2024-06-23 09:57 UTC, Mahmoud-Emad approved these changes

2024-06-24 13:22 UTC, maayarosama approved these changes

2024-06-24 13:25 UTC, zaelgohary approved these changes

2024-06-25 07:09 UTC, amiraabouhadid approved these changes

2024-06-25 07:12 UTC, merged