Improved styling and functionality of application cards display
threefoldtech/tfgrid-sdk-ts pull request #3003
Opened 2024-06-23 07:41 UTC by Mahmoud-Emad

### Description

Improved styling and functionality of application cards display

### Changes

- Introduced a new component called 'ApplicationCards' to manage the display of application cards.
- Implemented dynamic card height adjustment based on the tallest card to ensure consistent appearance.
- Added functionality to detect the current viewport size (mobile or desktop) and adjust card heights accordingly for better responsiveness and user experience.

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2907

### Screenshots/Video

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ab35cb8f-2c29-434a-a579-3982a59c0c66)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-06-23 09:56 UTC, samaradel commented on packages/playground/src/utils/types.ts
why do we need an interface for this? Props with required is enough no?

2024-06-23 10:51 UTC, amiraabouhadid requested changes
please make sure all text is completely visible at every screen size. text ("footprint") here is overflowing the card
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/9048933a-08f8-4a8a-bf48-883a8b318215)

2024-06-24 05:53 UTC, Mahmoud-Emad commented on packages/playground/src/utils/types.ts
The interface was there I just moved it into the right file, and yes it needed to infare the type of the object

2024-06-24 13:27 UTC, maayarosama approved these changes

2024-06-25 07:11 UTC, amiraabouhadid commented
@Mahmoud-Emad please fix merge conflicts

2024-06-25 08:04 UTC, Mahmoud-Emad commented on packages/playground/src/components/applications/ApplicationCards.vue
> +              </v-card-title>
IDK, it was there. I just created a component for the cards instead of duplicating them.

2024-06-25 08:12 UTC, 0oM4R commented on packages/playground/src/components/applications/ApplicationCards.vue
> +              </v-card-title>
i think there is no need for it any more, we can remove it as a part of the refactor

2024-06-25 08:26 UTC, Mahmoud-Emad commented on packages/playground/src/components/applications/ApplicationCards.vue
> +              </v-card-title>
Check please

2024-06-25 08:26 UTC, Mahmoud-Emad commented
> @Mahmoud-Emad please fix merge conflicts

Done, fixed

2024-06-25 08:55 UTC, 0oM4R approved these changes

2024-06-25 09:07 UTC, samaradel approved these changes

2024-06-25 10:04 UTC, amiraabouhadid requested changes
please make the spacing consistent with the other cards. for instance, the bottom spacing is much larger here 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/bbb3a9d7-5886-4827-8eca-b19d5a26d8da)
than here 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/2b8384ae-2a2d-4861-9db7-74037380b608)

2024-06-26 09:18 UTC, amiraabouhadid approved these changes

2024-06-26 09:19 UTC, merged