Development 2.6 update node price discount popup
threefoldtech/tfgrid-sdk-ts pull request #3028
Opened 2024-06-25 14:33 UTC by amiraabouhadid

### Changes
Updated node price and discount popup to include packages and price before/after discount

### Related Issues

#2805 

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [x] Screenshots/Video attached (needed for UI changes)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/937b8a2c-ea8c-4968-852a-368026a09cf7)

2024-06-26 07:40 UTC, zaelgohary reviewed
Build fails.

2024-06-26 07:59 UTC, Mahmoud-Emad approved these changes
Amazing ya Amiraaa

2024-06-26 09:05 UTC, AhmedHanafy725 requested changes

2024-06-26 09:05 UTC, AhmedHanafy725 commented on packages/playground/src/components/node_selector/TfNodeDetailsCard.vue
> +      { name: "Gold", discount: "-60%", tfts: 1000 },
The TFTs required to unlock the discount should be calculated based on the node resources.

2024-07-04 11:52 UTC, AhmedHanafy725 requested changes

2024-07-04 11:52 UTC, AhmedHanafy725 commented on yarn.lock
why do we have changes here? did we install a new package?

2024-07-04 11:54 UTC, amiraabouhadid commented on yarn.lock
I did but then I removed them

2024-07-04 11:58 UTC, AhmedHanafy725 commented
- I think we should show the price after the discount on the node card
- the price approximation should be ceil not floor
- I think we need something to say what is that table on the top 
- As a user why can't I see the required TFTs if I am not logged in
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/161aaad3-adee-47e9-b9aa-536ecbbe5784)

2024-07-07 03:13 UTC, amiraabouhadid commented
> * I think we should show the price after the discount on the node card
> * the price approximation should be ceil not floor
> * I think we need something to say what is that table on the top
> * As a user why can't I see the required TFTs if I am not logged in
>   ![image](https://private-user-images.githubusercontent.com/41957921/345821044-161aaad3-adee-47e9-b9aa-536ecbbe5784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjE5MDAsIm5iZiI6MTcyMDMyMTYwMCwicGF0aCI6Ii80MTk1NzkyMS8zNDU4MjEwNDQtMTYxYWFhZDMtYWRlZS00N2U5LWI5YWEtNTM2ZWNiYmU1Nzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAzMDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjgxZjUyNjc4MGMwY2YzMWJhMjczOThkYjZkMTk5YjlmMDJhZmQ2Y2Q0ZGNlZDAyZDY5NjM1NmM4YTFiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7JONkUw9S1vJueKCERPqjKKbl0SmmKmYxgiwqsV9T0)

good catch, fixed, thanks

2024-07-10 08:48 UTC, MohamedElmdary approved these changes

2024-07-10 14:24 UTC, AhmedHanafy725 commented on yarn.lock
ok then the changes in yarn.lock should be reverted

2024-07-10 14:26 UTC, AhmedHanafy725 commented
sometimes the TFTs required is 0 and sometimes it has a value
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/c264ab41-e9f5-4bd9-82bc-a76a20f796cd)

![Screenshot from 2024-07-10 17-19-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/53ce27c0-81a1-4ab4-9a76-43eb06090423)

2024-07-14 14:46 UTC, samaradel approved these changes

2024-07-15 11:27 UTC, AhmedHanafy725 approved these changes

2024-07-15 20:35 UTC, merged