add automated tests for presearch and algorand
threefoldtech/tfgrid-sdk-ts pull request #3030
Opened 2024-06-25 19:06 UTC by A-Harby

### Description

Add the automated tests for algorand and presearch application, (following same code struture as https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2890).

The tests are different in that they ssh to the deployed VM and assert that the application is running with the correct version and network.

2024-06-26 07:47 UTC, Mahmoud-Emad approved these changes

2024-06-27 08:42 UTC, amiraabouhadid approved these changes

2024-06-27 08:50 UTC, zaelgohary requested changes
I tried running Algorand test and it failed w this err. Is this normal? Same with Presearch.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/9aa063c0-08c1-4ffd-a383-45294948b4a3)

2024-06-27 14:14 UTC, A-Harby commented
> I tried running Algorand test and it failed w this err. Is this normal? Same with Presearch.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/343700838-9aa063c0-08c1-4ffd-a383-45294948b4a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTc4NTQsIm5iZiI6MTcxOTQ5NzU1NCwicGF0aCI6Ii80MDc3MDUwMS8zNDM3MDA4MzgtOWFhMDYzYzAtMDhjMS00ZmZkLWEzODMtNDUyOTQ5NDhiNGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE0MTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNWI2ZTM1MDc1YjViMDMwZGZlMjUxMDdhNmQ4MzIwNTRmZTY1ZDAzNDc3NWUwMGUyNzc1MDgyZjhiYTE4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dR6rU73hC9mZD8pD-mqXtY5jP92oLrC-ek6xq8jUoXk)

Did you use the correct SSH key type? you should use the ssh-ed25519 not the normal one.

2024-07-01 10:04 UTC, zaelgohary reviewed
The test would fail if SSH key needs permission.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/eb4bc574-6259-4164-ab34-8c8ce3df94d8)

2024-07-02 11:26 UTC, 0oM4R reviewed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d09fc4ef-4808-4816-8e19-13ccd74e6a8a)

this [package](https://www.npmjs.com/package/semver#prerelease-identifiers) may help

2024-07-02 11:34 UTC, 0oM4R reviewed
and please notice that the current logic overwrite the provided config if one of the `mnemonic`, `network`, or `ssh_key` are not provided in env.

we may change that logic to get the missing `only` form config.json 

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/828f0a0efacfd8a27e58a5befcd931782d2885f7/packages/grid_client/tests/client_loader.ts#L15-L26

2024-07-04 05:26 UTC, 0oM4R reviewed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/55fbd5f0-0b08-4579-9a48-4f70c3a49f90)

presearch failed

2024-07-04 05:26 UTC, 0oM4R commented on packages/grid_client/tests/config.json
remove those config please

2024-07-04 05:26 UTC, 0oM4R commented on packages/grid_client/tests/client_loader.ts
>  if (!network || !mnemonic || !ssh_key) {
this won't fix the issue, 
![Screenshot from 2024-07-04 08-10-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/387e085f-eec5-4747-b3ec-3c9a6e8783df)

i think its better to revert this changes and mention on docs that all credential must be in one place

2024-07-23 08:32 UTC, 0oM4R commented
can you please validate if the machine that runs these tests has ygg installed and configured, 
I forgot to install ygg and got some connection errors, It was unclear if it came from the deployment or from my side

2024-07-23 15:15 UTC, A-Harby commented
> can you please validate if the machine that runs these tests has ygg installed and configured, I forgot to install ygg and got some connection errors, It was unclear if it came from the deployment or from my side

As we discussed, I'm going to mention that on the Readme to make sure that ygg is needed to be installed with all of the other needed packages.

Also, I added a few tries in the trim of the Docker hash: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3030/commits/a3b4659951b9855546386019f4b30059e6116f8b.

2024-07-29 06:42 UTC, 0oM4R approved these changes

2024-07-29 12:15 UTC, zaelgohary approved these changes
Good job! @A-Harby

2024-07-29 12:16 UTC, merged