using any type instead of object
threefoldtech/tfgrid-sdk-ts pull request #3057
Opened 2024-06-30 16:13 UTC by maayarosama

### Description

Added a custom validation decorator accepting alphanumeric values and underscores

### Related Issues

#2303
### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-02 06:45 UTC, 0oM4R commented on packages/grid_client/src/helpers/validator.ts
> +function IsAlphanumericExceptUnderscore(validationOptions?: ValidationOptions) {
is underscore allowed or not? :D

2024-07-02 07:27 UTC, Mahmoud-Emad approved these changes

2024-07-02 08:23 UTC, amiraabouhadid reviewed
it isnt accepting underscore 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/b4c856a5-a6f5-4716-88a6-daeb4b8f2443)

2024-07-02 08:47 UTC, 0oM4R requested changes
` BaseGetDeleteModel` need to be updated as well

2024-07-02 08:57 UTC, 0oM4R reviewed
also `BaseGetDeleteModel` need to be updated
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4cf8e241-90a7-4d97-9c1a-8dfaaac377ff)

2024-07-03 07:34 UTC, amiraabouhadid requested changes

2024-07-03 07:34 UTC, amiraabouhadid commented on packages/playground/src/components/caprover_worker.vue
> +        validators.IsAlphanumericExpectUnderscore('Name should consist of letters ,numbers and undersocres only.'),
please change typo to "underscores".

2024-07-03 07:35 UTC, amiraabouhadid commented on packages/playground/src/weblets/freeflow.vue
> +          validators.IsAlphanumericExpectUnderscore('Name should consist of letters ,numbers and undersocres only.'),
here too

2024-07-03 09:41 UTC, Mahmoud-Emad commented
Please fix the conflicts

2024-07-07 07:21 UTC, amiraabouhadid approved these changes

2024-07-07 11:03 UTC, zaelgohary reviewed
I think the maxLength should be changed here:

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/8ea81fe95aa870ec9eca4ba72f8d84033191f626/packages/grid_client/src/modules/models.ts#L344

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/8ea81fe95aa870ec9eca4ba72f8d84033191f626/packages/grid_client/src/modules/models.ts#L237

2024-07-07 11:14 UTC, zaelgohary commented on packages/playground/src/weblets/tf_presearch.vue
>              validators.isAlphanumeric('Name should consist of letters and numbers only.'),
should be `IsAlphanumericExpectUnderscore`.

2024-07-07 11:15 UTC, zaelgohary commented on packages/playground/src/weblets/tf_subsquid.vue
>            validators.isAlphanumeric('Name should consist of letters and numbers only.'),
here too.

2024-07-08 07:11 UTC, zaelgohary approved these changes

2024-07-08 08:25 UTC, merged