Adding ubuntu 24.04 flist to full vm and micro vm as a default flist
threefoldtech/tfgrid-sdk-ts pull request #3099
Opened 2024-07-09 07:26 UTC by maayarosama

### Description

Adding ubuntu 24.04 flist to full vm and micro vm as a default flist

### Related Issues

- #3096
### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-10 09:30 UTC, zaelgohary submitted a review, later dismissed

2024-07-10 10:27 UTC, AhmedHanafy725 requested changes

2024-07-10 10:27 UTC, AhmedHanafy725 commented on packages/playground/src/weblets/full_vm.vue
> +              : [{ size: solution?.value.disk, mountPoint: "/" }, ...disks.value],
If we drop the solution disk from here, we should use it as rootfs instead.

2024-07-10 10:31 UTC, MohamedElmdary approved these changes

2024-07-15 09:11 UTC, AhmedHanafy725 submitted a review, later dismissed

2024-07-15 11:35 UTC, MohamedElmdary commented
@maayarosama data passed to `TfSelectionDetails` line#73 need to match whatever we pass in deploy function
so we need to pass solution disk as rootfs if needed and disks too

2024-07-16 08:00 UTC, amiraabouhadid submitted a review, later dismissed

2024-07-21 07:26 UTC, amiraabouhadid approved these changes

2024-07-21 08:54 UTC, zaelgohary approved these changes

2024-07-21 12:07 UTC, MohamedElmdary commented
@maayarosama tfselectiondetails still have same filters to getting node shouldn't we update it?

2024-07-22 07:52 UTC, maayarosama commented
> @maayarosama tfselectiondetails still have same filters to getting node shouldn't we update it?

can you elaborate more?

2024-07-23 08:56 UTC, MohamedElmdary approved these changes

2024-07-23 08:58 UTC, merged