Add billing docs
threefoldtech/tfgrid-sdk-ts pull request #3141
Opened 2024-07-21 10:01 UTC by maayarosama

### Description

Added billing docs to grid client

### Related Issues

- #3080
### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-08-01 11:38 UTC, zaelgohary requested changes
I think this document should be linked to the dedicated nodes when a user reserves a node. Additionally, it should be connected to the node contracts page and the calculation information for each solution.

2024-08-01 11:39 UTC, zaelgohary commented
Also, this should be in Playground docs not the Grid client.

2024-08-01 11:44 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +![image](https://user-images.githubusercontent.com/101194226/252134103-e7cce566-311d-4293-8e73-358d45b616d1.png)
Please update the image.

![image](https://github.com/user-attachments/assets/72056c4d-68b4-44a4-9d3c-ff1dd3cee064)

2024-08-01 11:44 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current CU value is `10 mUSD/h`, make sure that this value is updated according to the details section.
What does this mean?

2024-08-01 11:45 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current SU value is `5 mUSD/h`, make sure that this value is updated according to the details section.
here too.

2024-08-01 11:45 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current TFT value is `0.011 USD`, make sure that this value is updated according to the details section.
and here.

2024-08-01 11:45 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +Before assuming that the price above is the final price, check first if your twin is applicable for any of the available staking discount levels. to understand more about discount levels please check
Can we rephrase this?

2024-08-01 11:47 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current CU value is `10 mUSD/h`, make sure that this value is updated according to the details section.
here too.

2024-08-01 11:47 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current SU value is `5 mUSD/h`, make sure that this value is updated according to the details section.
and here.

2024-08-01 11:48 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +Before assuming that the price above is the final price, check first if your twin is applicable for any of the available staking discount levels. to understand more about discount levels please check
Please rephrase this.

2024-08-01 11:50 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +Before assuming that the price above is the final price, check first if your twin is applicable for any of the available staking discount levels. to understand more about discount levels please check
Rephrase this too.

2024-08-01 11:55 UTC, zaelgohary requested changes
While staking discounts are the same in all contracts, it's being repeated 3 times with dedicated nodes, node w public IP & with NU. Can we find a way to reduce the repetition?

2024-08-04 10:27 UTC, maayarosama commented
> I think this document should be linked to the dedicated nodes when a user reserves a node. Additionally, it should be connected to the node contracts page and the calculation information for each solution.

Per discussion with @AhmedHanafy725 this's not needed, as users can easily check the prices using the calculator

2024-08-08 07:10 UTC, amiraabouhadid commented on packages/grid_client/docs/billing.md
> +                       = 0.37727235000000003 TFT/hour
please use only 2 or 3 decimal places

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +These can be retrieved directly from the chain. Through the [polakdot UI](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.grid.tf#/chainstate).
```suggestion
These can be retrieved directly from the chain. Through the [Polakdot UI](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.grid.tf#/chainstate).
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +Lets assume that the resources for this deployment are:
```suggestion
Let's assume that the resources for this deployment are:
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +Network Usage is calculated for deployments with public ips, it's reprted every hour and its cost can be calculated approximatly as the value of data(sent + recieved) \* the NU value.
```suggestion
Network Usage is calculated for deployments with public IPs, it's reported every hour and its cost can be calculated approximately as the value of data(sent + received) \* the NU value.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +After than we can get the NU value. you can get its current value from the Pricing Policy.
```suggestion
After then we can get the NU value. you can get its current value from the Pricing Policy.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +Billing rate in the next hour should be: actual cost of the deployment + Total Netowrk Usage.
```suggestion
The billing rate in the next hour should be: the actual cost of the deployment + Total Network Usage.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +or directly through [stellar](https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?asset[]=TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVE
```suggestion
or directly through [Stellar](https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?asset[]=TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1&filter=markets&market=USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN-1).
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current TFT value is `0.012 USD`, please note that prices could be subjected to change.
```suggestion
The current TFT value is `0.012 USD`. Please note that prices could be subjected to change.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current SU value is `5 mUSD/h`, please note that prices could be subjected to change.
```suggestion
The current SU value is `5 mUSD/h`. Please note that prices could be subjected to change.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current CU value is `10 mUSD/h`, please note that prices could be subjected to change.
```suggestion
The current CU value is `10 mUSD/h`. Please note that prices could be subjected to change.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current SU value is `5 mUSD/h`, please note that prices could be subjected to change.
```suggestion
The current SU value is `5 mUSD/h`. Please note that prices could be subjected to change.
```

2024-08-11 10:15 UTC, zaelgohary commented on packages/grid_client/docs/billing.md
> +The current TFT value is `0.012 USD`, please note that prices could be subjected to change.
```suggestion
The current TFT value is `0.012 USD`. Please note that prices could be subjected to change.
```

2024-08-13 05:03 UTC, zaelgohary approved these changes

2024-08-14 12:23 UTC, amiraabouhadid approved these changes

2024-08-14 12:24 UTC, merged