Add ValidateMembers to all workloads
threefoldtech/tfgrid-sdk-ts pull request #3187
Opened 2024-07-31 08:56 UTC by zaelgohary

### Description

- Validate all workloads using ValidateMembers

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3038

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-31 09:24 UTC, AhmedHanafy725 requested changes
it should be added to all zos types classes that use the class validator

2024-07-31 10:01 UTC, zaelgohary commented
> it should be added to all zos types classes that use the class validator

All parent workloads have been validated. Validation of child workloads is unnecessary because the decorator handles the validation of nested workloads if ValidateNested is used. 


I removed the public IP from the network used in zmachine test to check if it would fail and it did.

![image](https://github.com/user-attachments/assets/fee58c93-21d8-45f6-8591-7b1924a31478)

2024-07-31 10:52 UTC, AhmedHanafy725 approved these changes

2024-08-01 12:08 UTC, amiraabouhadid approved these changes

2024-08-01 12:09 UTC, merged