Support council method on tfchain client
threefoldtech/tfgrid-sdk-ts pull request #3227
Opened 2024-08-05 15:25 UTC by AhmedHanafy725

### Description

- Support council proposals
- Support dao proposals
- Fix mapping events result in case the result was a list
- Support dev accounts other than `Alice`
- Support `forceTransfer` on balances module
- Support `cancelCollective` on smart contracts module

### Related Issues

- #3225 
- #3226 

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-08-06 12:14 UTC, Mahmoud-Emad requested changes

2024-08-06 12:14 UTC, Mahmoud-Emad commented on packages/tfchain_client/src/balances.ts
> +      throw new ValidationError("Amount must be a positive numeric value");
```suggestion
      throw new ValidationError("The amount must be a positive numeric value");

```

2024-08-06 12:14 UTC, Mahmoud-Emad commented on packages/tfchain_client/src/balances.ts
> +  async forceTransfer(options: BalanceForceTransferOptions) {
Can you please provide a docstring for this method?

2024-08-06 12:14 UTC, Mahmoud-Emad commented on packages/tfchain_client/src/contracts.ts
> +  @checkConnection
Here also, let's document this method too

2024-08-06 12:14 UTC, Mahmoud-Emad commented on packages/tfchain_client/src/contracts.ts
> +    }
Do you think we need to catch and return the error if there is an error, I'm thinking in case of failure

2024-08-06 12:14 UTC, Mahmoud-Emad commented on packages/tfchain_client/src/council.ts
> +  @checkConnection
Let's document this method also and please apply this to the whole file

2024-08-07 13:01 UTC, Mahmoud-Emad approved these changes
Good job ya Hanafy

2024-08-07 13:28 UTC, amiraabouhadid approved these changes

2024-08-07 13:29 UTC, merged