Support managing domains in the K8S application
threefoldtech/tfgrid-sdk-ts pull request #3312
Opened 2024-08-18 12:10 UTC by Mahmoud-Emad

### Description

The user might have some solutions on the cluster that require an ingress with a domain.

### Changes

- Optimized the `ManageGatewy` component to work on both types of machines normal `VM` and `K8S` machine
- Generate the name based on the master
- takes the master networks as the domain-supported networks
- Change the dialog title to be dynamic
- Working on refactoring the component

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3149

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-08-22 11:22 UTC, MohamedElmdary approved these changes

2024-08-25 09:06 UTC, amiraabouhadid commented on packages/playground/src/weblets/tf_deployment_list.vue
> +  console.log({ item });
why do we need this console.log?

2024-08-25 09:06 UTC, amiraabouhadid commented on yarn.lock
> +follow-redirects@^1.15.6:
why are there changes in this file?

2024-08-25 09:31 UTC, Omdaany commented on yarn.lock
> +follow-redirects@^1.15.6:
I just run yarn

2024-08-26 10:44 UTC, samaradel approved these changes

2024-08-27 17:52 UTC, amiraabouhadid requested changes

2024-08-27 17:52 UTC, amiraabouhadid commented on yarn.lock
> +  version "1.7.4"
please remove changes in this file as no new packages are required for the code above.

2024-08-28 13:32 UTC, amiraabouhadid approved these changes

2024-08-28 13:33 UTC, merged