Jenkins Application to Run on Threefold Grid
threefoldtech/tfgrid-sdk-ts pull request #3338
Opened 2024-08-25 16:13 UTC by amr-yassir

### Description

Added Jenkins Application to the Threefold Dashboard, allowing users to deploy Jenkins instances on the Grid.
Enabled passing Jenkins configuration parameters through environment variables.

![Screenshot 2024-08-25 183514](https://github.com/user-attachments/assets/5b611803-77ec-46d1-8585-cd6d215ec077)
![Screenshot 2024-08-25 183338](https://github.com/user-attachments/assets/e9c163bf-6d86-4327-a740-ac761ef3ba1d)

### Related Issues

- codescalersinternships/home/issues/245

### Documentation PR

- https://github.com/threefoldtech/info_grid/pull/629

### Checklist

- [ ] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

2024-08-26 07:42 UTC, zaelgohary requested changes

2024-08-26 07:42 UTC, zaelgohary commented on packages/playground/src/weblets/tf_deployment_list.vue
> +  { title: "Jenkins", value: "Jenkins", imgPath: "images/icons/jenkins.png" },
Action button should be added in the template.

2024-08-26 07:42 UTC, zaelgohary commented on packages/playground/src/weblets/jenkins.vue
> +const name = ref(generateName({ prefix: "fw" }));
```suggestion
const name = ref(generateName({ prefix: "jk" }));
```

2024-08-26 07:42 UTC, zaelgohary commented on packages/playground/src/weblets/jenkins.vue
> +const solution = ref() as Ref<SolutionFlavor>;
Use generatePassword.

2024-08-26 07:42 UTC, zaelgohary commented on packages/playground/src/weblets/jenkins.vue
> +const planetary = ref(false);
```suggestion
const planetary = ref(true);
```

2024-08-26 07:42 UTC, zaelgohary commented on packages/playground/src/constants/deployment_list.ts
> +    SSH_KEY: _ssh,
Include all env vars.

2024-08-26 07:42 UTC, zaelgohary commented on packages/playground/src/weblets/jenkins.vue
> +    layout.value.setStatus("deploy", "Rollbacking back due to fail to deploy gateway...");
```suggestion
    layout.value.setStatus("deploy", "Rolling back due to failure to deploy the gateway...");
```

2024-08-26 07:46 UTC, zaelgohary commented
I can't ssh to the machine.

![image](https://github.com/user-attachments/assets/2957cbd3-df35-41a9-bd47-b4312773fecd)

![image](https://github.com/user-attachments/assets/ae804e97-cc09-498a-b740-8a00dd91c42a)

2024-08-26 07:49 UTC, zaelgohary commented
Image specs should match.

![image](https://github.com/user-attachments/assets/1fb04a32-17a7-47aa-9626-3b73abc487d9)

![image](https://github.com/user-attachments/assets/9ac7508f-6961-4fca-b56b-8c5abb381d28)

2024-08-26 07:51 UTC, zaelgohary commented
Add planetary here too.

![image](https://github.com/user-attachments/assets/60587f56-459c-410b-a9cb-fd5600df3dac)

2024-08-26 08:13 UTC, zaelgohary commented on packages/playground/public/info/jenkins.md
> +Jenkins is a popular open-source automation server that enables developers to build, test, and deploy their applications continuously. For more details, check [Jenkins documentation](https://www.jenk
The link should be the one produced from the manual. It will be ''https://www.manual.grid.tf/documentation/dashboard/solutions/jenkins.html"

2024-08-26 10:58 UTC, amr-yassir commented
I noticed that all of the implemented applications use `Mycelium and IPv4 as networks, so would you like to initiate a new constant to display the Planetary network instead of the IPv4 specifically in this application?`

2024-08-26 11:02 UTC, amr-yassir commented
> Add planetary here too.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/361355432-60587f56-459c-410b-a9cb-fd5600df3dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Njg2OTcsIm5iZiI6MTcyNDY2ODM5NywicGF0aCI6Ii80MDc3MDUwMS8zNjEzNTU0MzItNjA1ODdmNTYtNDU5Yy00MTBiLWE5Y2ItZmQ1NjAwZGYzZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEwMzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYTM1NWNmODE5NWE4ZTg2ZTNjYjI1Yjk2YzQ4NzRhNTkwOWVjZTVhMzYwMTNmNGU5MzBmODFmMzlmMzc2MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bgxbl0rwKoyFAh0Opv_WFgVS6g0GaMVQ4Jl73gzOuqM)



> Add planetary here too.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/361355432-60587f56-459c-410b-a9cb-fd5600df3dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzA0MjMsIm5iZiI6MTcyNDY3MDEyMywicGF0aCI6Ii80MDc3MDUwMS8zNjEzNTU0MzItNjA1ODdmNTYtNDU5Yy00MTBiLWE5Y2ItZmQ1NjAwZGYzZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmNhOGRhYWIwMjU5ZTE4MmQ3Njk3NDlmN2MyNGMyZjhhYmI0NzMwYjVlOTk2ZGQzMjJiZjQwMTNhMzQ0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wid8fdqcBJZurfXGBN0M-ty4QBiRXctckhJRaCysO8w)

I noticed that all of the implemented applications use `Mycelium` and `IPv4` as networks, so would you like to initiate a new constant to display the `Planetary` network instead of the `IPv4` specifically in this application?

2024-08-26 11:03 UTC, amr-yassir commented
> Add planetary here too.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/361355432-60587f56-459c-410b-a9cb-fd5600df3dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzA0MjMsIm5iZiI6MTcyNDY3MDEyMywicGF0aCI6Ii80MDc3MDUwMS8zNjEzNTU0MzItNjA1ODdmNTYtNDU5Yy00MTBiLWE5Y2ItZmQ1NjAwZGYzZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmNhOGRhYWIwMjU5ZTE4MmQ3Njk3NDlmN2MyNGMyZjhhYmI0NzMwYjVlOTk2ZGQzMjJiZjQwMTNhMzQ0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wid8fdqcBJZurfXGBN0M-ty4QBiRXctckhJRaCysO8w)

I noticed that all of the implemented applications use `Mycelium` and `IPv4` as networks, so would you like to initiate a new constant to display the `Planetary` network instead of the `IPv4` specifically in this application?

2024-08-26 11:38 UTC, zaelgohary commented
> > Add planetary here too.
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/40770501/361355432-60587f56-459c-410b-a9cb-fd5600df3dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzA0MjMsIm5iZiI6MTcyNDY3MDEyMywicGF0aCI6Ii80MDc3MDUwMS8zNjEzNTU0MzItNjA1ODdmNTYtNDU5Yy00MTBiLWE5Y2ItZmQ1NjAwZGYzZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDExMDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmNhOGRhYWIwMjU5ZTE4MmQ3Njk3NDlmN2MyNGMyZjhhYmI0NzMwYjVlOTk2ZGQzMjJiZjQwMTNhMzQ0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wid8fdqcBJZurfXGBN0M-ty4QBiRXctckhJRaCysO8w)
> 
> 
> 
> I noticed that all of the implemented applications use `Mycelium` and `IPv4` as networks, so would you like to initiate a new constant to display the `Planetary` network instead of the `IPv4` specifically in this application?
> 
> 
> 
> For now, I added IPv4

Display ipv4 but make planetary's default value true.

2024-08-27 12:07 UTC, zaelgohary commented
@maxux Can you promote this flist? https://hub.grid.tf/amryassir.3bot/amryassir-jenkinsv3-latest.flist

2024-08-27 12:08 UTC, zaelgohary reviewed
All good! will approve once flist gets promoted & doc PR gets merged. Good job! @amr-yassir

2024-08-27 12:24 UTC, maxux commented
Which target name ? `tf-official-apps/jenkinsv3-latest.flist` ?

2024-08-27 12:27 UTC, zaelgohary commented
> Which target name ? `tf-official-apps/jenkins-latest.flist` ?

2024-08-27 13:59 UTC, 0oM4R requested changes
great solution! thank you for the great job
I think we have to follow up the Wireguard requirements in #3287

2024-08-27 13:59 UTC, 0oM4R commented on packages/playground/src/weblets/jenkins.vue
> +          name => validators.isAlpha('Name must start with alphabet char.')(name[0]),
```suggestion
         (name: string) => validators.isAlpha('Name must start with an alphabetical character.')(name[0]),
```


as we agreed on [#3287 ](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3287#discussion_r1730291955)

2024-08-27 14:00 UTC, 0oM4R commented on packages/playground/src/weblets/jenkins.vue
> +          name => validators.isAlpha('Name must start with alphabet char.')(name[0]),
please do it also on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3338/files#diff-fc3e26378b57a55a0c7e60ae1fed09033c71b6acc8f96d0a85a85e5e00b10d4cR36 as well

2024-08-27 17:02 UTC, maxux commented
https://hub.grid.tf/tf-official-apps/jenkins-latest.flist.md
Sorry for the delay

2024-08-28 11:33 UTC, 0oM4R commented on packages/playground/src/weblets/jenkins.vue
> +          name => validators.isAlpha('Name must start with alphabet char.')(name[0]),
> please do it also on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3338/files#diff-fc3e26378b57a55a0c7e60ae1fed09033c71b6acc8f96d0a85a85e5e00b10d4cR36 as well

@amr-yassir

2024-08-28 13:32 UTC, zaelgohary approved these changes

2024-08-28 15:22 UTC, 0oM4R approved these changes

2024-08-28 21:16 UTC, merged