Add release date for the applications
threefoldtech/tfgrid-sdk-ts pull request #3493
Opened 2024-10-02 11:52 UTC by samaradel

### Description

- Add release date for the applications or Gitea, Jenkins, Jitsi, Nostr, static website, and TFrobot.
- Remove importing ```nextTick``` as it's not used anymore.

### Changes

![image](https://github.com/user-attachments/assets/4d6a48db-8230-4eb6-9e67-a825f2b97b9e)

![image](https://github.com/user-attachments/assets/a9482e88-c8f5-43bb-a322-c22a21810657)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3448

### Tested Scenarios

- The ```new``` label now is on ```Gitea, Jenkins, Jitsi, Nostr, static website, and TFrobot``` and it will be expired after 30 days.

### To consider

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-10-02 12:11 UTC, 0oM4R requested changes
jitsi is not added

2024-10-02 12:13 UTC, 0oM4R commented
also Domains solution should have the icon, please add it or open an issue for it

2024-10-02 12:16 UTC, 0oM4R commented
some solutions cards is not responsive, works fine on staging 
![image](https://github.com/user-attachments/assets/0e3b145a-c2aa-48f4-ae82-8410896c5d7e)

2024-10-02 13:09 UTC, samaradel commented
> also Domains solution should have the icon, please add it or open an issue for it

added

2024-10-02 13:10 UTC, samaradel commented
@0oM4R create an issue please for https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3493#issuecomment-2388500470 as it's not a part of this issue.

2024-10-02 14:26 UTC, 0oM4R commented
i commented with that on the original issue and reopened it  

> @0oM4R create an issue please for [#3493 (comment)](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3493#issuecomment-2388500470) as it's not a part of this issue.

2024-10-02 14:28 UTC, 0oM4R approved these changes
added and works fine on both themes

![Screenshot from 2024-10-02 17-25-40](https://github.com/user-attachments/assets/d86b1df0-ec8e-45c3-84d2-82b0bd633394)
![Screenshot from 2024-10-02 17-25-46](https://github.com/user-attachments/assets/ef4827d9-c40f-4493-be2f-c95516f95036)

2024-10-10 09:51 UTC, AhmedHanafy725 approved these changes

2024-10-10 09:51 UTC, merged