update max name length from 50 to 35
threefoldtech/tfgrid-sdk-ts pull request #3549
Opened 2024-10-23 08:29 UTC by amiraabouhadid

### Changes

- changed max name length in deployment model in client
- changed max name length in all deployment dashboard validation

### Related Issues

#2364

### Tested Scenarios

- entered a name longer than 35 chars in dashboard deployments

2024-10-23 11:47 UTC, samaradel approved these changes

2024-10-24 09:37 UTC, 0oM4R reviewed
![image](https://github.com/user-attachments/assets/d7cbd962-8cfd-468a-b575-e93a62ef3e76)

is there a reason for gitea to be only 15 char ?

2024-10-24 12:48 UTC, amiraabouhadid commented
> ![image](https://private-user-images.githubusercontent.com/62248851/379709909-d7cbd962-8cfd-468a-b575-e93a62ef3e76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzM3NzAsIm5iZiI6MTcyOTc3MzQ3MCwicGF0aCI6Ii82MjI0ODg1MS8zNzk3MDk5MDktZDdjYmQ5NjItOGNmZC00NjhhLWI1NzUtZTkzYTYyZWYzZTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDEyMzc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0N2EzN2QxN2I1NzNhNWUwMDM0MGIyZmE3YzFjNWZjNDQyNDUxMjlhMDFkZWQxYzU0OTkwOTk1NzkxNzVmODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dgL6tFYtOFL1p7QyZRUxIW2b9ryx_hjkIVOsNXbOxko)
> 
> is there a reason for gitea to be only 15 char ?

good question, for node pilot too @zaelgohary ?

2024-10-28 07:59 UTC, zaelgohary commented
> 
> > is there a reason for gitea to be only 15 char ?
> 
> 
> 
> good question, for node pilot too @zaelgohary ?

I'm not sure if node pilot has another restriction rule on its own but you may try to deploy and check if it works.

2024-10-28 08:23 UTC, amiraabouhadid commented
@0oM4R  changing gitea and node pilot name max length to 35 and deploying throws this error 

![image](https://github.com/user-attachments/assets/e906a556-923c-4315-9f9c-3d721239ef92)

![image](https://github.com/user-attachments/assets/db050bd7-de50-48f4-868d-57716eace8f5)

so won't be changing gitea and node pilot max length from 15 to 35

2024-10-29 10:34 UTC, 0oM4R commented
i think we need to handle gatewaynameModal length, i see it got changed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/c5f1bad1c09934f276e88c53980a82e17b3ce3fa#diff-13f46ac7ceefb9f9d1ca1a680d587fccdb952ec2a5c94eea64c2cce762236927R237) 

it is happening with matermost 
![Uploading Screenshot from 2024-10-29 13-32-50.png…]()

2024-10-29 10:34 UTC, 0oM4R requested changes
i think we need to handle gatewaynameModal length, i see it got changed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/c5f1bad1c09934f276e88c53980a82e17b3ce3fa#diff-13f46ac7ceefb9f9d1ca1a680d587fccdb952ec2a5c94eea64c2cce762236927R237) 

it is happening with matermost 
![Screenshot from 2024-10-29 13-32-50](https://github.com/user-attachments/assets/1990f755-393b-456c-861e-98a43697a8e3)

2024-10-29 12:49 UTC, amiraabouhadid commented
@0oM4R good catch, got validation error for more than 36 chars indeed
![image](https://github.com/user-attachments/assets/6165539d-715f-44e6-89b3-67470aa31476)
it has been set to 35 char max now

2024-10-29 13:54 UTC, 0oM4R reviewed
i think we have to update gatewaynameModel to accept the namelength + length of the domain @AhmedHanafy725  can you please provide numbers here ? 

this was already exists but I don't know why it got removed
after manage that please update gitea and node pilot domain names

2024-11-04 09:12 UTC, 0oM4R commented on packages/playground/src/weblets/tf_domains.vue
no need to be 15 here as the name here is the gateway name lets make it 35

![image](https://github.com/user-attachments/assets/2e4b6205-080c-4a2b-bc87-d822e7b296a7)

2024-11-04 09:42 UTC, amiraabouhadid commented on packages/playground/src/weblets/tf_domains.vue
done 
![image](https://github.com/user-attachments/assets/058a6227-b410-4c77-bdb8-9e6e6dc17199)

2024-11-04 09:59 UTC, 0oM4R approved these changes

2024-11-04 10:30 UTC, samaradel approved these changes

2024-11-04 10:31 UTC, merged