Fix adding worker with mycelium to k8s
threefoldtech/tfgrid-sdk-ts pull request #3565
Opened 2024-10-30 14:22 UTC by samaradel

### Description

- Check if ```myceliumNetworkSeed.seed``` is existed.
- Remove ```.skip``` from ```add worker``` test case.

### Changes

![image](https://github.com/user-attachments/assets/bfe918aa-f266-40ad-8aa5-d2deef14ad36)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3509

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-11-12 09:50 UTC, 0oM4R requested changes
please update the PR description to include tested scenarios.
and brief  about the original couase of the issue will be great

2024-11-19 14:44 UTC, ramezsaeed approved these changes

2024-11-21 13:10 UTC, 0oM4R reviewed
tests are still failing 
![Screenshot from 2024-11-21 13-19-42](https://github.com/user-attachments/assets/6635b588-dd78-4c8b-a881-c20eda887793)

2024-12-02 12:15 UTC, samaradel commented
![image](https://github.com/user-attachments/assets/ed993f3e-2089-47ac-92c9-7b78d4ddedc6)
works now

2024-12-05 13:06 UTC, maayarosama commented
I get the following error while trying to run the test, I suggest that it might be a good idea to to read the network, mnemonics and ssh key straight from the config file 
![Screenshot from 2024-12-05 14-57-52](https://github.com/user-attachments/assets/ffbae1cd-817c-4672-b226-5f01e0b25b71)

2024-12-08 09:19 UTC, samaradel commented
> I get the following error while trying to run the test, I suggest that it might be a good idea to to read the network, mnemonics and ssh key straight from the config file ![Screenshot from 2024-12-05 14-57-52](https://private-user-images.githubusercontent.com/66883096/392826994-ffbae1cd-817c-4672-b226-5f01e0b25b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NDk3MjQsIm5iZiI6MTczMzY0OTQyNCwicGF0aCI6Ii82Njg4MzA5Ni8zOTI4MjY5OTQtZmZiYWUxY2QtODE3Yy00NjcyLWIyMjYtNWYwMWUwYjI1YjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDA5MTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYmJkMmQzZTI0YmM0ZjNmYzI0YjY3N2JiNjU0OTMyM2E0Yjk5ZjQ1MWFmYTdlMTJlMTIyOWFlZDdmNzMyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ylv_RkNO6__aMd6lXNG_8r0XHQQTHJxEI-uMzYmjJ1I)

I'm not sure if we should do that, I see it implemented that way in many scripts.. @AhmedHanafy725 what do you think?

2024-12-08 11:31 UTC, AhmedHanafy725 commented
> > I get the following error while trying to run the test, I suggest that it might be a good idea to to read the network, mnemonics and ssh key straight from the config file ![Screenshot from 2024-12-05 14-57-52](https://private-user-images.githubusercontent.com/66883096/392826994-ffbae1cd-817c-4672-b226-5f01e0b25b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NDk3MjQsIm5iZiI6MTczMzY0OTQyNCwicGF0aCI6Ii82Njg4MzA5Ni8zOTI4MjY5OTQtZmZiYWUxY2QtODE3Yy00NjcyLWIyMjYtNWYwMWUwYjI1YjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDA5MTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYmJkMmQzZTI0YmM0ZjNmYzI0YjY3N2JiNjU0OTMyM2E0Yjk5ZjQ1MWFmYTdlMTJlMTIyOWFlZDdmNzMyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ylv_RkNO6__aMd6lXNG_8r0XHQQTHJxEI-uMzYmjJ1I)
> 
> I'm not sure if we should do that, I see it implemented that way in many scripts.. @AhmedHanafy725 what do you think?

it's required for the ssh package, but it should be mentioned clearly in the docs that we should generate an ed25519 sshkey in the correct path. Please create an issue for it

2024-12-09 10:23 UTC, ramezsaeed commented
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3565#issuecomment-2525673735

its menstioned in the tests here to use ed25519 sshkey:

- https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/tests/README.md
- https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/docs/tests.md

2024-12-15 12:42 UTC, closed without merging