Fix zmount test cases
threefoldtech/tfgrid-sdk-ts pull request #3608
Opened 2024-11-10 12:58 UTC by samaradel

### Description

Fix zmount test suite expected errors.

### Changes
![image](https://github.com/user-attachments/assets/7f1ed529-12a7-4f03-ae23-cab40be99598)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3523

### Tested Scenarios

- Update the value of size to get errors

### Checklist

- [x] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

2024-11-11 09:28 UTC, xmonader commented on packages/grid_client/tests/modules/zmount.test.ts
> +    expect(result).toBe(size.toString());
can directly do expect(zmount.challenge()).toBe....

2024-11-11 09:28 UTC, xmonader commented on packages/grid_client/tests/modules/zmount.test.ts
>      const size = 100 * 1025 ** 4;
What do these numbers mean? try extracting to a const

2024-11-11 09:37 UTC, xmonader commented on packages/grid_client/tests/modules/zmount.test.ts
>      const size = 1.5;
is that 1.5 byte?

2024-11-11 09:40 UTC, xmonader commented on packages/grid_client/tests/modules/zmount.test.ts
>    test("Size empty value.", () => {
While we are at it, check against null, undefined, NaN, {} , and []

2024-11-11 09:41 UTC, xmonader commented on packages/grid_client/tests/modules/zmount.test.ts
> +          max: "size must not be greater than 10995116277760",
check against the boundaries max, and min

and off by 1 min - 1 and max+1

2024-11-11 09:41 UTC, xmonader requested changes
We need to use better descriptions to describe the cases better

2024-11-11 13:38 UTC, 0oM4R approved these changes
passed locally, not sure about the tests description 
![image](https://github.com/user-attachments/assets/8930b63d-2e54-444a-b678-4a5674ff0173)

2024-11-24 10:04 UTC, amiraabouhadid commented on packages/grid_client/tests/modules/zmount.test.ts
> +    it("should fail validation if size is less than the minimum", async () => {
shouldn't we have a test to test if input size is int?

2024-11-24 10:08 UTC, amiraabouhadid commented on packages/grid_client/tests/modules/zmount.test.ts
> +      expect(result).toBe("5368709120");
without checking if size is int , the challenge can return any special chars in the string, no?

2024-11-24 10:09 UTC, amiraabouhadid commented on packages/grid_client/tests/modules/zmount.test.ts
> +      expect(() => (zmount.size = 15 * 1024 ** 4)).toThrow();
define the min and max as constants before any of the tests

2024-11-24 12:14 UTC, ramezsaeed approved these changes

2024-11-25 13:58 UTC, amiraabouhadid commented
please place the min and max values in a constant before any of the tests. Please move tests that check if size is null, Nan or not an int before the min and max tests

2024-11-26 09:58 UTC, maayarosama approved these changes

2024-12-02 15:53 UTC, amiraabouhadid approved these changes

2024-12-03 06:05 UTC, AhmedHanafy725 requested changes
you should add a test for setting a floating number

2024-12-03 06:05 UTC, AhmedHanafy725 commented on packages/grid_client/tests/modules/zmount.test.ts
> +  const validSize = 5 * 1024 ** 3;
it's better to have a random size (within a certain range) to test with

you can use this method to generate the random number https://github.com/threefoldtech/tfgrid-sdk-ts/blob/f9a5b06796073bcd61ef729240308d122beb3646/packages/grid_client/src/helpers/utils.ts#L18

2024-12-05 12:24 UTC, ramezsaeed approved these changes

2024-12-05 14:46 UTC, maayarosama commented on packages/grid_client/tests/modules/zmount.test.ts
> +  const validSize = 5 * 1024 ** 3;
Why are we initializing this with a value, if we're using getRandomNumber

2024-12-08 10:44 UTC, AhmedHanafy725 commented on packages/grid_client/tests/modules/zmount.test.ts
> +      expect(typeof result).toBe("string");
you can cast `validSize` to string and check against its value

2024-12-15 09:52 UTC, AhmedHanafy725 approved these changes

2024-12-16 09:20 UTC, maayarosama approved these changes

2024-12-18 09:59 UTC, merged