Add deployment scripts for Gitea, Jenkins, Jitsi, and Nostr
threefoldtech/tfgrid-sdk-ts pull request #3689
Opened 2024-12-01 05:10 UTC by khaledyoussef24

### Description

Describe the changes introduced by this PR and what does it affect
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3330

adding scripts for 

- [ ] Gitea
- [ ] Jenkins
- [ ] Jitsi
- [ ] Nostr

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Tested Scenarios

A list of scenarios tried to match the deliverables

### Documentation PR

For UI changes, Please provide the Documetation PR on [info_grid](https://github.com/threefoldtech/info_grid)

### To consider

#### Preliminary Checks:

- Does it completely address the issue linked?
- What about edge cases?
- Does it meet the specified acceptance criteria?
- Are there any unintended side effects?
- Does the PR adhere to the team's coding conventions, style guides, and best practices?
- Does it integrate well with existing features?
- Does it impact the overall performance of the application?
- Are there any bottlenecks or slowdowns?
- Has it been optimized for efficiency?
- Has it been adequately tested with unit, integration, and end-to-end tests?
- Are there any known defects or issues?
- Is the code well-documented?
- Are changes to documentation reflected in the code?

#### UI Checks:

- If a UI design is provided/ does it follow it?
- Does every button work?
- Is the data displayed logical? Is it what you expected?
- Does every validation work?
- Does this interface feel intuitive?
- What about slow network? Offline?
- What if the gridproxy/graphql/chain is failing?
- What would a first time user have a hard time navigating here?

#### Code Quality Checks:

- Code formatted/linted? Are there unused imports? .. etc
- Is there redundant/repeated code?
- Are there conditionals that are always true or always false?
- Can we write this more concisely?
- Can we reuse this code? If yes, where?
- Will the changes be easy to maintain and update in the future?
- Can this code become too complex to understand for other devs?
- Can this code cause future integration problems?

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-12-08 10:00 UTC, maayarosama requested changes

2024-12-08 10:00 UTC, maayarosama commented on packages/grid_client/scripts/applications/gitea.ts
I get a Gateway Timeout when trying to access an instance deployed from with the script https://gt79newgitea.gent01.dev.grid.tf , https://gt79newgitea2.gent01.dev.grid.tf/
while everything works fine when deploying from the dashboard https://gt79gtett7l.gent01.dev.grid.tf/

2024-12-12 17:51 UTC, khaledyoussef24 commented on packages/grid_client/scripts/applications/gitea.ts
will check the scripts and try the deployment again

2024-12-15 11:17 UTC, 0oM4R commented
as @khaledyoussef24  request will convert it to draft

2024-12-17 07:53 UTC, khaledyoussef24 commented
Work in progress
- made the deployment of gitea to work on public ip
- tried and debugged every proccess to make it run using mycelium but didnot work
- test jenkins working fine
- jitsi is configured right and checked it
- nostor also works fine

2024-12-18 07:51 UTC, khaledyoussef24 commented on packages/grid_client/scripts/applications/gitea.ts
fixed resolve but it only works with public ip

2024-12-18 11:24 UTC, maayarosama requested changes

2024-12-18 11:24 UTC, maayarosama commented on packages/grid_client/scripts/applications/gitea.ts
> +    backends: [`http://[${VMmyceliumIP}]:3000`],
This results in an error since you removed VMmyceliumIP

2024-12-18 11:24 UTC, maayarosama commented on packages/grid_client/scripts/applications/nostor.ts
nostor is giving me bad gateway

2024-12-30 08:03 UTC, khaledyoussef24 commented
will split PRs because facing an issue with nostr always giving bad gate way even when the port is opened
https://github.com/threefoldtech/tf-images/issues/313

2025-01-01 06:59 UTC, 0oM4R commented on packages/grid_client/scripts/applications/gitea.ts
> +          GITEA__HOSTNAME: domain,
Why are those lines commented?

2025-01-01 07:41 UTC, khaledyoussef24 commented on packages/grid_client/scripts/applications/gitea.ts
> +          GITEA__HOSTNAME: domain,
in case you used smtp server only they shall be uncommented

2025-01-02 13:42 UTC, 0oM4R reviewed
gitea and jenkins works fine, but jitsi is not reachable gives bad gateway

2025-01-02 14:43 UTC, khaledyoussef24 commented
> gitea and jenkins works fine, but jitsi is not reachable gives bad gateway

there is a related issue that the jitsi image is not working will update it later once it works
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3662

2025-01-05 11:06 UTC, 0oM4R approved these changes
jenkins and gitea works fine

2025-01-12 09:42 UTC, maayarosama approved these changes

2025-01-12 14:19 UTC, merged