Add rentableOrRentedBy query in dedicated filter
threefoldtech/tfgrid-sdk-ts pull request #3740
Opened 2024-12-15 13:22 UTC by samaradel

### Description

- Add ```rentableOrRentedBy``` query in the dedicated filter.
- merging development branch.

### Changes

[Screencast from 04-11-24 16:30:07.webm](https://github.com/user-attachments/assets/c5001aec-fd6d-4afc-87bd-0191c51fab53)

### Tested Scenarios

- Go to any solution page
- Toggle on the Dedicated node switch
- Load Nodes and you'll find the nodes you already rented and the nodes that are available for you to rent

### Scenarios Update

- Rent a node and make sure it's not listed in the free dedicated nodes filter.
- Unreserve the node and ensure it is back in the free dedicated node filter.
- Try to deploy on a node not rented by you (should fail with proper error message)

### Documentation PR
- https://github.com/threefoldtech/info_grid/issues/705

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2775

### Checklist

- [x] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

2024-12-15 13:22 UTC, samaradel commented
cpd from https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3587

2024-12-16 09:11 UTC, 0oM4R reviewed
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3587#pullrequestreview-2504519058
still reproducable 
![Screenshot from 2024-12-16 11-08-35](https://github.com/user-attachments/assets/73dc3d47-6dc2-48fd-9f01-1756ae613389)
![Screenshot from 2024-12-16 11-08-21](https://github.com/user-attachments/assets/f9662649-d113-4b54-81ac-9c17a8e7e7a4)


also there are many unrelated changes please make sure to update the pr

2024-12-17 10:17 UTC, maayarosama commented
Please remove unrelated changes

2024-12-29 11:50 UTC, amiraabouhadid commented
it correctly shows my rented node along with any rentable node in the node selector in deployment 
![Screenshot from 2024-12-29 13-44-20](https://github.com/user-attachments/assets/771e8e30-ca3a-4d1e-bf0b-e7cc4a02855b)
however, i can click deploy on a node that isnt rented by me and the error would only be shown after deployment has been initiated 
![Screenshot from 2024-12-29 13-44-20](https://github.com/user-attachments/assets/b84ec374-d0f4-4241-93f6-e16636830173)
shouldn't the error be shown in node selector and deployment prevented if node is not rented by you?

2025-01-01 12:42 UTC, samaradel commented
@amiraabouhadid fixed, please check the attached video

2025-01-02 07:37 UTC, 0oM4R requested changes
I see some files that have unrelated changes; please remove them

2025-01-02 07:37 UTC, 0oM4R commented on packages/playground/src/utils/nodeSelector.ts
> +    if (node.dedicated || node.rentedByTwinId === 0) {
i think it should be and 
I'm already reting node 151 but got this error
<img width="877" alt="image" src="https://github.com/user-attachments/assets/85fdd079-3b28-407e-a5bb-c6b0b1465c45" />

2025-01-12 09:26 UTC, maayarosama commented on .github/workflows/yarn_audit.yml
why is there changes in this file?

2025-01-13 13:44 UTC, 0oM4R requested changes
please resolve the conflicts

2025-01-13 16:13 UTC, samaradel commented on .github/workflows/yarn_audit.yml
I see it's about spaces and formats, I'll discard it all

2025-01-14 13:44 UTC, 0oM4R requested changes
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/7d761c8f-bb27-4a6f-b8df-cbcf390f67a9" />

2025-01-14 14:38 UTC, samaradel commented
please pull the latest changes

2025-01-14 15:08 UTC, 0oM4R commented
If no nodes rented and i toggled on the dedicated filter it will list the rentable nodes, but will select randome one of them, then will show it as invalid as it is not rented, if this is not related to the pr please open an issue to prevent the autoselection in this case.

2025-01-28 10:22 UTC, maayarosama approved these changes

2025-01-29 08:17 UTC, 0oM4R reviewed
https://github.com/user-attachments/assets/9f7821d3-06ed-4119-8ae3-08b40894da99


idk how but now it list shared nodes

2025-01-30 09:06 UTC, 0oM4R commented
> Screen.Recording.2025-01-29.at.10.13.48.AM.mov 
> 
> idk how but now it list shared nodes

works fine now

2025-01-30 09:11 UTC, 0oM4R commented
please make sure we need this change 
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3740/files#diff-6b6be54e76d51117b494941ba7cc8c428b7bfb0109a8b297b111ac4e6c4f0696

2025-01-30 09:20 UTC, 0oM4R approved these changes

2025-01-30 09:29 UTC, merged