Handle rented node in grace period
threefoldtech/tfgrid-sdk-ts pull request #3742
Opened 2024-12-15 13:26 UTC by samaradel

### Description

Check if the rented node contract is in the grace period when listing the node.

### Changes

![image](https://github.com/user-attachments/assets/1f1b3866-ee34-4737-84bf-b43fbef80cbe)

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3025

### Tested Scenarios

- Navigate to the Node finder page.
- Rent a dedicated node.
- Leave it till it goes to the grace period.
- Navigate to any solution.
- Try to deploy an instance on the rented node.

### Checklist

- [x] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [x] Screenshots/Video attached (needed for UI changes)

2024-12-15 13:26 UTC, samaradel commented
cpd from https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3646

2024-12-16 09:25 UTC, 0oM4R reviewed
![image](https://github.com/user-attachments/assets/87581bb5-5060-4d81-a904-f30e9dba31fa)


https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3646#pullrequestreview-2504471530

2024-12-16 11:43 UTC, samaradel commented
@0oM4R check it, it already fixed

2024-12-16 15:55 UTC, amiraabouhadid approved these changes
no console err 
![image](https://github.com/user-attachments/assets/30ba6a57-8ca9-4b79-b126-37762a303438)

2025-02-03 15:11 UTC, 0oM4R reviewed
on first if the node is selected; 
we won't see any error but if you select another node then click on the graceperiod node will see the error


also the error must be handled 

- the node is not a valid node; so we shouldn't auto select it; need to handle this case as well 




![image](https://github.com/user-attachments/assets/d5483656-9649-4842-be1e-2281755d8326)

2025-02-03 15:15 UTC, 0oM4R commented on packages/playground/src/utils/nodeSelector.ts
> +        });
i don't think we need to add timeout here, not the auto one there is no toast overlap what do you think?

2025-02-17 10:43 UTC, samaradel commented on packages/playground/src/utils/nodeSelector.ts
> +        });
totally agree, removed

2025-02-17 12:02 UTC, 0oM4R commented on packages/playground/src/utils/nodeSelector.ts
> +        });
I see you removed timeout in the automatic on to, can you explain why I think ti is a better UX even if we set it to only one sec

2025-02-17 12:03 UTC, 0oM4R requested changes
![graceperiod](https://github.com/user-attachments/assets/fb377ad3-ebd9-494e-a113-e264aa3618ea)


error still exsist if i select the grace period node

2025-02-18 00:53 UTC, samaradel commented
@0oM4R works with me, please make sure to have the latest update and build

2025-02-18 08:36 UTC, 0oM4R commented
https://github.com/user-attachments/assets/f8faaada-8999-4d4d-8585-6b940c0b4958

2025-02-20 14:49 UTC, 0oM4R requested changes
I think we just need the changes in utils only; no need for the other changes

2025-02-20 14:49 UTC, 0oM4R commented on packages/playground/src/components/node_selector/TfAutoNodeSelector.vue
>          const rentContractValid = props.filters.dedicated ? await validateRentContract(gridStore, node) : true;
we already do the same in validateRentContract is there any extra logic added in the new added lines above

2025-02-20 14:49 UTC, 0oM4R commented on packages/playground/src/components/node_selector/TfNodeDetailsCard.vue
> +
why we are calling `validateRentContract` here while it is already on the manual and auto node finder?
![image](https://github.com/user-attachments/assets/b8064b4f-bc43-4011-be27-a0c6b309a827)
i think we need to make it just emit the select event and the parent component will handle the validation

2025-02-20 14:49 UTC, 0oM4R commented on packages/playground/src/utils/nodeSelector.ts
>      if (node.rentContractId !== 0) {
I suggest having early return here if the node is not rented and not in a dedicated farm, so there is no need to continue, right?

just a reminder that the dedicated node in shared farm can be used as shared node

2025-02-23 11:15 UTC, samaradel commented on packages/playground/src/components/node_selector/TfAutoNodeSelector.vue
>          const rentContractValid = props.filters.dedicated ? await validateRentContract(gridStore, node) : true;
I see it only fires when `props.filters.dedicated` is on and with our latest changes in the dashboard we can have a  dedicated node in the normal list, not sure if we should remove it

2025-02-23 11:15 UTC, samaradel commented on packages/playground/src/components/node_selector/TfNodeDetailsCard.vue
> +
same reason https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3742/files#r1966744835

2025-02-23 11:55 UTC, 0oM4R commented on packages/playground/src/components/node_selector/TfAutoNodeSelector.vue
>          const rentContractValid = props.filters.dedicated ? await validateRentContract(gridStore, node) : true;
so we should change this condition to be applicable with the latest changes; My point is we shouldn't do any validation inside the details card; in some cases we will do the same validation twice! on inside the details card and the other in the parent component

2025-02-23 11:56 UTC, samaradel commented on packages/playground/src/components/node_selector/TfAutoNodeSelector.vue
>          const rentContractValid = props.filters.dedicated ? await validateRentContract(gridStore, node) : true;
agreed

2025-02-23 14:35 UTC, 0oM4R approved these changes
dedicated nodes in shared farms are valid nodes 
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/75710324-9621-43d6-aab1-9d6072e7b5e2" />

validation works fine on automatic finder 

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/4f8e6399-2b17-4e00-bac1-cad2beebd75e" />


all works fine thanks.


<img width="1249" alt="image" src="https://github.com/user-attachments/assets/69784fbb-9684-4525-94e7-a4299e1cc6ec" />

2025-02-24 13:42 UTC, ramezsaeed approved these changes

2025-02-24 13:48 UTC, merged