Fix worker's name
threefoldtech/tfgrid-sdk-ts pull request #3745
Opened 2024-12-15 13:32 UTC by samaradel

### Description

Rename worker after successful deployment

### Changes

- Create another worker's name after the deployment ends.

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3670

### Tested Scenarios

Deploy a worker on any orchestrator instance. Don't close the dialog; instead, switch to the deploy tab and deploy another worker.

### Checklist

- [x] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-12-15 13:35 UTC, samaradel commented
cpd from https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3685

2024-12-19 12:43 UTC, maayarosama approved these changes

2024-12-22 11:48 UTC, amiraabouhadid requested changes
tried to deploy a second worker without closing dialog, got this error
![image](https://github.com/user-attachments/assets/bee97b0a-6253-4730-bba4-8b13f0a3e1b8)

2024-12-25 12:36 UTC, samaradel commented
@amiraabouhadid it works fine with me, please try again and ensure you have the latest code.

2024-12-29 13:57 UTC, maayarosama approved these changes

2024-12-29 19:27 UTC, 0oM4R reviewed
[Screencast from 2024-12-29 21-21-14.webm](https://github.com/user-attachments/assets/94114572-b86a-4698-8a6b-6e6a851e79f5)

the branch is updated with the remote one, i treid every thing to make sure that I'm on the correct branch, i notice that the branch name is similar to the old one maybe this is the problem

2024-12-30 16:38 UTC, samaradel commented
@0oM4R @amiraabouhadid I got it now, you guys are trying it on Caprover and it is fixed on k8s only, now it is fixed on Caprover too.

2025-01-01 11:32 UTC, 0oM4R requested changes
not working with me it stuck on this
![image](https://github.com/user-attachments/assets/dbcbb0aa-a826-48c9-8cc7-afc35bc50321)

2025-01-01 13:53 UTC, samaradel commented
@0oM4R fixed now

2025-01-01 14:45 UTC, 0oM4R commented
> @0oM4R fixed now

its not enough the selected node is the same, which may lead to a resource error. 
i got this error, the name got changed but the selected node is not updated.
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/75cdb85e-5b43-4bd7-bc9e-8ee506a3e743" />

2025-01-08 16:49 UTC, samaradel commented
build failed because of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3791

2025-01-12 09:20 UTC, maayarosama requested changes
![Screenshot from 2025-01-12 11-19-35](https://github.com/user-attachments/assets/b23a874b-5bb6-4e1b-be13-c0e4e2e19be4)

2025-02-19 13:11 UTC, closed without merging