Added Hex seed to profile manager
threefoldtech/tfgrid-sdk-ts pull request #3765
Opened 2024-12-19 13:34 UTC by maayarosama

### Description

Added Hex seed to profile manager

### Related Issues

- #3706
### Tested Scenarios

- Connect your wallet and check profile manager, hex seed will be shown

### To consider

#### Preliminary Checks:

- [ ] Preliminary Checks
  - Does it completely address the issue linked?
  - What about edge cases?
  - Does it meet the specified acceptance criteria?
  - Are there any unintended side effects?
  - Does the PR adhere to the team's coding conventions, style guides, and best practices?
  - Does it integrate well with existing features?
  - Does it impact the overall performance of the application?
  - Are there any bottlenecks or slowdowns?
  - Has it been optimized for efficiency?
  - Has it been adequately tested with unit, integration, and end-to-end tests?
  - Are there any known defects or issues?
  - Is the code well-documented?
  - Are changes to documentation reflected in the code?

#### UI Checks:

- [ ] UI Checks
  - If a UI design is provided/ does it follow it?
  - Does every button work?
  - Is the data displayed logical? Is it what you expected?
  - Does every validation work?
  - Does this interface feel intuitive?
  - What about slow network? Offline?
  - What if the gridproxy/graphql/chain is failing?
  - What would a first time user have a hard time navigating here?

#### Code Quality Checks:

- [ ] Code Quality Checks
  - Code formatted/linted? Are there unused imports? .. etc
  - Is there redundant/repeated code?
  - Are there conditionals that are always true or always false?
  - Can we write this more concisely?
  - Can we reuse this code? If yes, where?
  - Will the changes be easy to maintain and update in the future?
  - Can this code become too complex to understand for other devs?
  - Can this code cause future integration problems?

### Testing Checklist

- [ ] Does it Meet the specified acceptance criteria.
- [ ] Test if changes can affect any other functionality.
- [ ] Tested with unit, integration, and end-to-end tests.
- [ ] Tested the un-happy path and rollback scenarios.
- [ ] Documentation updated to meet the latest changes.
- [ ] Check automated tests working successfully with the changes.
- [ ] Can be covered by automated tests.

### General Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring
- [ ] Screenshots/Video attached (needed for UI changes)

2024-12-22 09:14 UTC, amiraabouhadid commented on packages/playground/src/weblets/profile_manager.vue
> +              <VTextField label="Your Hex Seed" readonly v-model="profileManager.profile.hexSeed" v-bind="props" />
please add a tooltip with the hint that user needs to use the hex seed to import in TFconnect as mentioned in the issue

2024-12-22 09:34 UTC, amiraabouhadid requested changes
when i try to copy the hex seed, it copies the twin id instead 
https://www.loom.com/share/fb7ab0efdbb1477692f7c4c3cd05dee0?sid=9dd49c30-c317-4088-be73-2142cc2fc92f

2024-12-23 10:40 UTC, amiraabouhadid commented on packages/playground/src/weblets/profile_manager.vue
> +                tooltip="Please use your hex seed to import your wallet in the Threefold mobile application."
```suggestion
                tooltip="Please use this hex seed to import your wallet in <a href="https://www.manual.grid.tf/documentation/threefold_token/storing_tft/tf_connect_app.html" > Threefold Connect.</a>"
```

2024-12-24 11:46 UTC, amiraabouhadid reviewed
the link in the tooltip isn't clickable

2024-12-24 12:04 UTC, maayarosama commented
> the link in the tooltip isn't clickable

The tooltip itself is clickable

2024-12-24 12:23 UTC, ramezsaeed reviewed
Test scenarios:
- use the Hex seed to import the wallet in tf connect app.
- Test with account has 24 word mnemonics not only 12 words and test also vise versa from the app to dash board and from the  dashboard to the app.

2024-12-25 12:44 UTC, samaradel commented
![image](https://github.com/user-attachments/assets/f414dec4-a4df-4292-a1fa-106bf7d3466d)
- the QR part must also be centralized vertically to fit the new data and the divider.

2024-12-29 10:55 UTC, maayarosama commented
> Test scenarios:
> 
> * use the Hex seed to import the wallet in tf connect app.
> * Test with account has 24 word mnemonics not only 12 words and test also vise versa from the app to dash board and from the  dashboard to the app.

As I don't have an account with 24 words, it was agreed with @ramezsaeed to skip this test

2024-12-29 11:30 UTC, amiraabouhadid commented
> > the link in the tooltip isn't clickable
> 
> The tooltip itself is clickable

yes but the link to threefold connect isnt working, fix it or remove the link please

2024-12-29 13:50 UTC, maayarosama commented
> > > the link in the tooltip isn't clickable
> > 
> > 
> > The tooltip itself is clickable
> 
> yes but the link to threefold connect isnt working, fix it or remove the link please

Th tooltip itself is working. If I add a link to the word (Threefold connect) I'll have to use  ```<v-tooltip>``` instead of ```<input-tooltip>``` which conflicts with ```<CopyInputWrapper>```, so I'll just remove the link

2024-12-29 14:07 UTC, ramezsaeed approved these changes

2024-12-30 08:04 UTC, amiraabouhadid approved these changes

2024-12-30 14:18 UTC, 0oM4R requested changes
If i log in with the hex seed, the mnemonic field will show me the hex seed as well

![image](https://github.com/user-attachments/assets/f2589d09-97d8-40d0-9084-d4e59ef26287)

2025-01-12 13:02 UTC, 0oM4R approved these changes
![image](https://github.com/user-attachments/assets/65d7d7bc-da2c-4c93-a8f9-d03d546b746b)


works good now, thank you;

2025-01-12 13:25 UTC, samaradel approved these changes

2025-01-12 14:09 UTC, merged

2025-01-15 07:30 UTC, atefnazmy commented
> > the link in the tooltip isn't clickable
> 
> The tooltip itself is clickable

- The tooltip is not clickable