fix dedicate and bridge tests
threefoldtech/tfgrid-sdk-ts pull request #807
Opened 2023-07-13 15:48 UTC by A-Harby

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-07-18 18:14 UTC, A-Harby commented
[7418dc5](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/807/commits/7418dc5fcaada8c35661c244e254e9c647b3330a) Fixing failing tests from the [workflow](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5576018733/jobs/10186704415)

2023-07-20 12:16 UTC, mohamedamer453 approved these changes

2023-07-25 07:31 UTC, mohamedamer453 requested changes

2023-07-25 07:31 UTC, mohamedamer453 commented on packages/dashboard/tests/frontend_selenium/requirements.txt
> +requests==2.31.0
Versions should also be updated in the [docs](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/dashboard/docs/selenium.md#selenium)

2023-07-25 07:40 UTC, mohamedamer453 approved these changes

2023-07-25 08:13 UTC, AhmedHanafy725 approved these changes

2023-07-25 08:13 UTC, merged