Support transfer with twin Id
threefoldtech/tfgrid-sdk-ts pull request #815
Opened 2023-07-17 09:02 UTC by AlaaElattar

2023-07-17 09:04 UTC, AlaaElattar commented
![Screenshot from 2023-07-17 12-02-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/a6d10c19-bec9-47b4-9ff3-850b580c7e2a)
![Screenshot from 2023-07-17 12-03-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/e3f0988f-439a-44e8-a33d-f548987722a3)
![Screenshot from 2023-07-17 12-03-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/5494449
![Screenshot from 2023-07-17 12-03-45](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/7ba89425-c387-43a7-97df-d4d576fdeabf)
1/97b75340-5844-426e-8b61-8bbd3a1e0aeb)

2023-07-17 14:09 UTC, AhmedHanafy725 requested changes
in case the twin doesn't exist, no errors and the `submit` button is active but does nothing

2023-07-17 14:09 UTC, AhmedHanafy725 commented on packages/dashboard/src/portal/views/Transfer.vue
> +                    () => transferTwinIdCheck() || 'invalid address',
this field should have also validation to be only positive integer numbers

2023-07-25 08:01 UTC, AhmedHanafy725 commented
the validation sometimes works and sometimes not 

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/584e1a06-7c91-42f4-be09-d67e8c87a4b0

2023-07-30 12:45 UTC, AhmedHanafy725 commented on packages/dashboard/src/portal/views/Transfer.vue
> +    const injector = await web3FromAddress(this.$store.state.credentials.account.address);
it's still using the extension while it's gone on the development branch, so please merge the development branch into this branch and use the mnemonic instead

2023-07-31 13:27 UTC, closed without merging