Development transfer by twin
threefoldtech/tfgrid-sdk-ts pull request #889
Opened 2023-07-31 13:22 UTC by AlaaElattar

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-08-01 12:39 UTC, AlaaElattar commented
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/2d6da7f5-8897-474c-a469-a43840d60847)
![Screenshot from 2023-08-01 15-36-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/30dadf6f-e238-41f7-93c1-fa5bb1365a79)
![Screenshot from 2023-08-01 15-36-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/5b012776-5bdf-4d1e-b3e2-2e3d1b71ebb0)
![Screenshot from 2023-08-01 15-36-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/95deb7c8-70ed-491c-9b5a-3eda8cb52c3b)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/d1894228-8bdc-45a5-a777-02186e372320)
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/572

2023-08-01 13:31 UTC, AhmedHanafy725 requested changes

2023-08-02 09:52 UTC, 0oM4R commented on packages/dashboard/src/portal/components/TransferTextField.vue
> +    value: {
can you change this name ? to make the code more readable

2023-08-02 10:07 UTC, 0oM4R commented on packages/dashboard/src/portal/views/Transfer.vue
> +import Buttons from "../components/TransferFormButtons.vue";
also here we can name it `TransferFormButtons` to make it clear in the template

2023-08-02 12:15 UTC, 0oM4R approved these changes

2023-08-02 12:23 UTC, AhmedHanafy725 approved these changes

2023-08-02 13:09 UTC, merged