add error msg for dedicated nodes
threefoldtech/tfgrid-sdk-ts pull request #908
Opened 2023-08-03 10:49 UTC by AlaaElattar

2023-08-03 10:59 UTC, AlaaElattar commented
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/ff3e575a-ca3b-4a03-9d99-e5a89ba80696



https://github.com/threefoldtech/tfgrid-sdk-ts/issues/887

2023-08-03 11:02 UTC, xmonader commented on packages/playground/src/components/select_node.vue
> +      There are no nodes rented by you that match your selected resources, try to change your resources or rent a node
Let's update to
```
You have no nodes rented that match your selected resources; try changing your selected resources or renting a node matching your requirements.
```

2023-08-03 11:08 UTC, xmonader approved these changes

2023-08-03 13:27 UTC, AlaaElattar commented on packages/playground/src/components/select_node.vue
> +        (selectedNode && props.filters.rentedBy) ||
when user waited for node to relaod and then choose dedicated, the alert didn't appear

2023-08-03 15:29 UTC, zaelgohary requested changes

2023-08-06 10:04 UTC, zaelgohary approved these changes

2023-08-06 10:21 UTC, AhmedHanafy725 approved these changes

2023-08-06 10:22 UTC, merged