fix transferring to same twin or address
threefoldtech/tfgrid-sdk-ts pull request #910
Opened 2023-08-03 12:19 UTC by AlaaElattar

![Screenshot from 2023-08-03 15-13-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/408e180a-8f61-4381-a653-bc6ee9f2f723)
![Screenshot from 2023-08-03 15-13-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/b06a61dd-d245-4d83-9428-c86fc6c4ddbb)
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/909

2023-08-06 09:39 UTC, AhmedHanafy725 requested changes
it's working well, but the messages need to be updated when the reason is changed.
for example: 
- set the address to mine -> `You can't transfer to yourself`
- if the address is removed, the message will remain the same while it should be `This field is required`

2023-08-06 13:20 UTC, AlaaElattar commented
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f0afd57e-fe36-42df-b8e0-de448a61f410

2023-08-06 14:07 UTC, AhmedHanafy725 requested changes

2023-08-06 14:07 UTC, AhmedHanafy725 commented on packages/dashboard/src/portal/views/Transfer.vue
> +    }
the rest error messages should be handled here too and removed from the form's rules?

2023-08-07 06:35 UTC, AhmedHanafy725 approved these changes

2023-08-07 06:36 UTC, merged