Add a condition before getGPUInfo, Fix nodeId
threefoldtech/tfgrid-sdk-ts pull request #915
Opened 2023-08-06 09:53 UTC by zaelgohary

### Description

Fix getGPUInfo

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/881

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2023-08-06 11:13 UTC, AhmedHanafy725 reviewed
in case the full vm doesn't have a gpu and tries to load the info from the deployment list, it keeps loading forever.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/1a564053-86ae-4e4c-a5c1-0e4f45c346ca)

2023-08-09 08:59 UTC, AhmedHanafy725 commented on packages/playground/src/weblets/tf_contracts_list.vue
> +    }
why do we do these calls we already have the info we need to show?

2023-08-09 09:06 UTC, 0oM4R commented on packages/playground/src/components/deployment_data_dialog.vue
> +contract.value.metadata?.includes("fullvm") ? getGPUInfo() : undefined;
__Suggestion__: this line is functional and will work, but i believe it's not the most clear or common way to structure this kind of logic. there are more readable alternatives that can improve code readability and maintainability
for example: 
`if(contract.value.metadata?.includes("fullvm"))  getGPUInfo();`

2023-08-10 08:25 UTC, AhmedHanafy725 requested changes

2023-08-10 08:25 UTC, AhmedHanafy725 commented on packages/grid_client/src/clients/tf-grid/contracts.ts
> +                  id
`gridVersion` and `id` are not useful to the user, let's remove them

2023-08-10 08:25 UTC, AhmedHanafy725 commented on packages/grid_client/src/clients/tf-grid/contracts.ts
> +                  gridVersion
here too let's remove `gridVersion` and `id`

2023-08-10 08:36 UTC, AhmedHanafy725 commented
when trying to get the contract's details of a full vm from the contract list, I got this error
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/3317929c-8fb1-45a2-9abd-8d0f117df1ed)

2023-08-10 15:16 UTC, AhmedHanafy725 approved these changes

2023-08-10 15:16 UTC, merged