add validation for mnemonics on diff network
threefoldtech/tfgrid-sdk-ts pull request #936
Opened 2023-08-08 11:15 UTC by amiraabouhadid

### Description

added mnemonic verification method to check if user provided mnemonics are for a user on the current network.

### Changes

- added a watcher for mnemonic that assigns public variable this.grid to gridclient fetched from entered mnemonics
- added a verification function to mnemonics rules to check if the returned grid has a twinId. If it doesnt then there isnt a user on the current network. 
- Profile manager now displays a `Couldn't find a user for provided mnemonic on ${config.network} network.` for invalid mnemonics that are bip39 compliant but do not belong to a user on the current network

### Related Issues

fixes issue #894 

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/4fdff4cd-301d-47c2-ae74-8f2ac6e88839)

2023-08-09 09:21 UTC, 0oM4R reviewed
- if i paste my mnem it show the invalid message and the logs contain many errors, once i delete it and paste it again it works fine
- also on any change we have an error in the logs i believe we can handle it 
 
[Screencast from 09 أغس, 2023 EEST 12:16:56 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/722e695f-ad5b-4395-a3d9-c6c0c5371adb)

2023-08-09 09:21 UTC, 0oM4R commented on packages/dashboard/src/components/TfChainConnector.vue
> +    console.log(this.mnemonic);
__Question__: is there any need for logging the mnemonic here ?

2023-08-10 12:52 UTC, amiraabouhadid commented
<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/1a7743feff954ae9bdcc0f55549aadde?sid=d4fa4b77-1fbc-4833-97bc-f8a0e7fa9afb" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

2023-08-10 14:26 UTC, MohamedElmdary commented
@amiraabouhadid I think we should disable `connect` button while validating using watcher as user might click it

2023-08-10 16:07 UTC, 0oM4R requested changes

2023-08-10 16:07 UTC, 0oM4R commented on packages/dashboard/src/components/TfChainConnector.vue
> +      this.mnemonicError = `Couldn't find a user for provided mnemonic on ${config.network} network.`;
For better UX we can show 'Mnemonic is required' as an error message when the field is empty 
```suggestion
       if(!this.mnemonic) this.mnemonicError = "Mnemonic is required"
      else this.mnemonicError = `Couldn't find a user for provided mnemonic on ${config.network} network.`;
```

2023-08-13 11:48 UTC, Omarabdul3ziz commented
- `connect` button still not disabled if no mnemonic is provided. only if i write something and remove it `Mnemonic is required` message appears and and `connect` get disabled.
  ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32527347/e4437214-979f-499b-b3d1-428b403cacba)

apart from that all looks good

2023-08-13 11:58 UTC, Omarabdul3ziz approved these changes

2023-08-13 12:56 UTC, 0oM4R approved these changes

2023-08-13 13:39 UTC, AhmedHanafy725 approved these changes

2023-08-13 13:39 UTC, merged